simdutf/simdutf

include/simdutf/simdutf_version.h

Refs: https://github.com/simdutf/simdutf/issues/78#issuecomment-892714203

Fix SIMDUTF_VERSION value

---

.gitignore

Add amalgamated source files to .gitignore

---

include/simdutf/internal/isadetection.h

I determined[1] that the code I work on uses only AVX512{F,CD,DQ}, thus
added only these three extensions to `instruction_set` enum. On the other
hand, listed all AVX512 feature bits for future use. Purposely omitted
AVX512BF, as we won't use 16-bit floating point for conversion.
[1] Software Development Emulator allows to gather information which
extensions were used during execution of given app. We simply run:
$ sde -mix -- ./program
$ grep AVX512 sde-mix-out.txt

Add runtime detection of AVX512 extension

---

src/haswell/avx2_convert_utf16_to_utf8.cpp
tests/validate_utf16_basic_tests.cpp

https://github.com/simdutf/simdutf/issues/92

verifying issue 92

---

src/generic/utf8_to_utf16/valid_utf8_to_utf16.h
tests/convert_utf8_to_utf16_tests.cpp
tests/convert_valid_utf8_to_utf16_tests.cpp

Derives from https://github.com/simdutf/simdutf/pull/111

fix valid_utf8_to_utf16.h producing invalid utf16 (issue111)

---

benchmarks/src/benchmark_base.cpp
benchmarks/src/event_counter.h
benchmarks/src/linux-perf-events.h

This PR will be merged and is recommended.

We use simpler performance counters. Under graviton 2, you may only access two counters at a time

---

src/icelake/icelake-utf8-common.inl.cpp

This allows us to transcode (from UTF-8) emojis at gigabytes per second!

cleaning 4-byte case

---

src/icelake/icelake-from-utf8.inl.cpp
src/icelake/icelake-from-valid-utf8.inl.cpp
src/icelake/icelake-macros.inl.cpp
src/icelake/icelake-utf8-common.inl.cpp

This will add some performance by reducing a bit the instruction count.

unmasking the writes

---

src/icelake/icelake_utf8_common.inl.cpp

This PR reduces very slightly the number of instructions in some cases under both GCC and LLVM. Performance is largely unaffected, except that there are noticeable gains in some cases under GCC (+2%). Note that neither GCC nor LLVM dominate: in some cases, one is better than the other.
```
first the new code, then the old code
We start with GCC 12
unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
0.669 ins/byte,    0.669 cycle/byte,    4.687 GB/s (0.3 %),     3.410 GHz,    0.920 ins/cycle 
0.669 ins/byte,    0.669 cycle/byte,    4.686 GB/s (0.3 %),     3.410 GHz,    0.920 ins/cycle 
unicode_lipsum/lipsum/Chinese-Lipsum.utf8.txt
1.229 ins/byte,    1.229 cycle/byte,    5.369 GB/s (0.4 %),     3.416 GHz,    1.931 ins/cycle 
1.308 ins/byte,    1.308 cycle/byte,    5.263 GB/s (0.3 %),     3.413 …
```

More minor tweaking to UTF-8 to UTF-16 icelake transcoder

---

AUTHORS

Now that the icelake kernels are in, I believe this is appropriate.

AUTHORS: add self

---

src/icelake/icelake_utf8_common.inl.cpp

Over some inputs dominated by 1-byte and 2-byte UTF-8 characters, the icelake utf-8 to utf-16 transcoder has very low instruction/cycle count. The reason is a long dependency chain. We can break the chain at the expense of a higher instruction count.
The idea is that we load 64 bytes with each iteration, and if we detect that they are made of 1-byte or 2-byte characters, then we always decode fully the set of characters (between 16 and 32) that begin in the first 32 bytes of our input. Of course, that's pessimistic because we can often process much more if there are few ASCII (1-byte) characters.
For lipsum/Arabic, this change pushes our from ~4.7 GB/s to 7.8 GB/s under GCC and from 5.0 GB/s to 7.6 GB/s under LLVM.
My approach is simplistic and might be improved, but the gains appear …

Improving drastically the performance of the utf-8 to utf-16 icelake transcoder in some cases

---

include/simdutf/implementation.h

context: https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/49707/console

fix: remove extra semi

---

README.md
include/simdutf/implementation.h
src/implementation.cpp

The last release broke the Node.js builds. Upon request from @addaleax, I'm adding new function that handles the endianness.
Fixes: https://github.com/nodejs/node/pull/46208

feat: add endian aware convert functions

---

benchmarks/src/benchmark.cpp
benchmarks/src/benchmark_base.cpp
benchmarks/stream.cpp
include/simdutf/implementation.h
src/implementation.cpp
tests/helpers/test.cpp

This might help with some static initialization issues. See https://github.com/nodejs/node/pull/46256
cc @anonrig  @addaleax 
Fixes: https://github.com/simdutf/simdutf/issues/87

Fix static initialization.

---

.github/workflows/vs17-clang-ci.yml
include/simdutf/internal/isadetection.h

@StefanStojanovic could you test/review?
Fixes https://github.com/simdutf/simdutf/issues/216

Fixing support for Windows ARM64

---

.github/workflows/macos-latest.yml

builds out fine, https://github.com/chenrui333/simdutf/actions/runs/4267007544
relates to https://github.com/Homebrew/homebrew-core/pull/124086
cc @lemire

workflows: add macos build

---

cmake/simdutf-flags.cmake
tests/CMakeLists.txt
tests/random_fuzzer.cpp
tests/special_tests.cpp

We already had a fuzzer, but this one is dedicated to testing our code with garbage inputs.

Adding a random fuzzer

---

.gitignore

For people using a GUI, it is useful to have a .gitignore with good defaults.

Adding vs code to gitignore

---

include/simdutf/internal/isadetection.h

Fixes https://github.com/simdutf/simdutf/issues/242
Note that the commit is attributed to @easyaspi314

Detecting if the OS supports AVX-512.

---

src/scalar/utf8_to_utf16/utf8_to_utf16.h
src/scalar/utf8_to_utf32/utf8_to_utf32.h

Fixes https://github.com/simdutf/simdutf/issues/245

Fix for issue 245

---

.github/workflows/ubuntu22-cxx20.yml
.github/workflows/vs17-ci-cxx20.yml
CMakeLists.txt
cmake/simdutf-flags.cmake
src/simdutf/arm64/simd.h
src/simdutf/haswell/simd.h
src/simdutf/ppc64/simd.h
src/simdutf/westmere/simd.h
tests/bele_tests.cpp

Adding CXX 20 tests

---

src/CMakeLists.txt

Propagating warning flags to consumers seems like a pretty big anti-pattern to me.

Don't propagate warning flags to consumers

---

.github/workflows/vs17-ci-cxx20.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml
src/simdutf/fallback/bitmanipulation.h
tools/sutf.cpp

Seemingly, folks still want to use 32-bit Windows.

---

src/generic/utf16.h
src/icelake/icelake_convert_utf16_to_utf32.inl.cpp

Probably inconsequential, but @aqrit suggested that we fix those in another PR, and I think it is probably wise.

Minor fixes

---

.github/workflows/msys2.yml
benchmarks/CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt
tools/CMakeLists.txt

Fixes https://github.com/simdutf/simdutf/issues/331

Remove the 'static' keyword

---

.github/workflows/armv7.yml

adding armv7 to CI

---

fuzz/roundtrip.cc

Fundamentally a coverage driven fuzzer is an optimization algorithm, where the goal-state is 100% code coverage. As it currently stands this fuzzer is trying to optimize it's input so that is valid UTF-8 AND UTF-16be/le. By giving each function/encoding-source it's own independent input we allow the fuzzer to optimize coverage for each function individually.

fuzz: Give fuzzer independent data per func

---

include/simdutf/error.h

Fixes https://github.com/simdutf/simdutf/issues/350

fixing issue 350

---

.github/workflows/aarch64.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu20sani.yml
.github/workflows/ubuntu22.yml
.github/workflows/ubuntu22_gcc12.yml
.github/workflows/vs16-ci.yml
.github/workflows/vs17-arm-ci.yml
.github/workflows/vs17-ci-cxx20.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml
cmake/simdutf-flags.cmake
src/CMakeLists.txt
src/arm64/arm_base64.cpp
src/fallback/implementation.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/386

fixing padding issue

---

include/simdutf/error.h
src/error.cpp
tests/readme_tests.cpp

Fix https://github.com/simdutf/simdutf/issues/388

fix issue 388

---

CMakeLists.txt

add tests to ensure that simdutf does not contain unwanted symbols

---

README.md
include/simdutf/implementation.h

Just making the API clearer with better comments.

Improve the latin1 documentation

---

include/simdutf/internal/isadetection.h

Fixes https://github.com/simdutf/simdutf/issues/419

fix: remove namespaced header include (issue 419)

---

README.md
include/simdutf/implementation.h

This is a README update.
cc @Constellation

improving the documentation of base64 standards.

---

src/icelake/implementation.cpp
tests/random_fuzzer.cpp
tests/validate_utf16be_with_errors_tests.cpp

fix: correct AVX-512 UTF-32 validator

---

src/arm64/arm_convert_utf16_to_utf32.cpp
src/arm64/arm_convert_utf16_to_utf8.cpp
src/generic/buf_block_reader.h
src/generic/utf8_validation/utf8_lookup4_algorithm.h
src/haswell/avx2_convert_utf16_to_utf32.cpp
src/haswell/avx2_convert_utf16_to_utf8.cpp
src/haswell/avx2_convert_utf8_to_latin1.cpp
src/icelake/icelake_utf8_validation.inl.cpp
src/implementation.cpp
src/scalar/utf8_to_latin1/utf8_to_latin1.h
src/simdutf/haswell.h
src/westmere/sse_convert_utf16_to_utf8.cpp
src/westmere/sse_convert_utf32_to_utf8.cpp
src/westmere/sse_convert_utf8_to_latin1.cpp
src/westmere/sse_validate_utf16.cpp

fix: remove utf-8 to latin 1 optimization that might be dangerous + removing contraction

---

src/icelake/icelake_convert_utf16_to_utf8.inl.cpp
tests/convert_utf16be_to_utf8_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/443

fix: use an int for adjust instead of the unsigned size_t type

---

src/icelake/implementation.cpp
tests/convert_utf16be_to_utf8_with_errors_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/445

fix Issue 445

---

src/icelake/implementation.cpp
tests/validate_utf8_with_errors_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/458

fix for issue 458

---

fuzz/roundtrip.cpp
src/scalar/base64.h
tests/random_fuzzer.cpp

additional tests for the safe base64 decoder

---

.github/workflows/ubuntu24sani_clang.yml
src/arm64/arm_convert_latin1_to_utf16.cpp
src/arm64/arm_convert_latin1_to_utf32.cpp
src/arm64/arm_convert_utf16_to_latin1.cpp
src/arm64/arm_convert_utf16_to_utf32.cpp
src/arm64/arm_convert_utf16_to_utf8.cpp
src/arm64/arm_convert_utf32_to_latin1.cpp
src/arm64/arm_convert_utf32_to_utf16.cpp
src/arm64/arm_detect_encodings.cpp
src/haswell/avx2_convert_utf16_to_latin1.cpp
src/haswell/avx2_convert_utf16_to_utf32.cpp
src/haswell/avx2_convert_utf16_to_utf8.cpp
src/haswell/avx2_convert_utf32_to_utf16.cpp
src/haswell/avx2_convert_utf32_to_utf8.cpp
src/haswell/avx2_detect_encodings.cpp
src/icelake/icelake_ascii_validation.inl.cpp
src/icelake/icelake_convert_utf16_to_latin1.inl.cpp
src/icelake/icelake_convert_utf32_to_latin1.inl.cpp
src/icelake/icelake_convert_utf32_to_utf16.inl.cpp
src/icelake/icelake_convert_utf32_to_utf8.inl.cpp
src/icelake/implementation.cpp
src/westmere/sse_convert_latin1_to_utf32.cpp
src/westmere/sse_convert_utf16_to_latin1.cpp
src/westmere/sse_convert_utf16_to_utf32.cpp
src/westmere/sse_convert_utf16_to_utf8.cpp
src/westmere/sse_convert_utf32_to_utf16.cpp
src/westmere/sse_convert_utf32_to_utf8.cpp
src/westmere/sse_detect_encodings.cpp
tests/convert_utf16be_to_utf8_with_errors_tests.cpp
tests/convert_utf16le_to_utf32_with_errors_tests.cpp

Trying to verify issue 468
cc @pauldreik

verify issue 468

---

src/scalar/base64.h
tests/base64_tests.cpp

fix: correct problem where some non-ascii chars could be allowed in UTF-16 base64

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

After merging this PR, we will release version 5.3.2.

preparing release 5.3.2

---

src/scalar/utf8_to_latin1/utf8_to_latin1.h
src/scalar/utf8_to_utf16/utf8_to_utf16.h
src/scalar/utf8_to_utf32/utf8_to_utf32.h
tests/convert_utf8_to_latin1_with_errors_tests.cpp
tests/convert_utf8_to_utf16be_with_errors_tests.cpp
tests/convert_utf8_to_utf16le_with_errors_tests.cpp
tests/convert_utf8_to_utf32_with_errors_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/483

fix issue 483

---

riscv/Dockerfile
riscv/README.md
riscv/remove-docker-station
riscv/run-docker-station

Will be useful in the future if we want to keep on developing the  RISC-V kernel.

chore: document how to run tests with RISC-V using QEMU

---

src/icelake/implementation.cpp
tests/convert_utf8_to_latin1_with_errors_tests.cpp

adds test for https://github.com/simdutf/simdutf/issues/493

adding test case for issue 493

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

* Fix bad result on empty input passed to validate functions by @pauldreik in https://github.com/simdutf/simdutf/pull/491
* make convert_valid_utf32_to_latin1 scalar correct and consistent by @pauldreik in https://github.com/simdutf/simdutf/pull/494
* adding test case for issue 493 by @lemire in https://github.com/simdutf/simdutf/pull/497

Patch release 5.3.5

---

src/arm64/arm_base64.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/scalar/base64.h
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/503

fix for issue 503

---

src/icelake/implementation.cpp
tests/detect_encodings_tests.cpp

fixes https://github.com/simdutf/simdutf/issues/516

fixing issue 516

---

fuzz/CMakeLists.txt
fuzz/base64.cpp
fuzz/helpers/common.h

This adds a fuzzer for the base64 related functions. This fuzzer has found a few issues which have been fixed so the fuzzer seems to run clean at least on amd64.

add base64 fuzzer

---

scripts/base64/neon_decode.py
src/arm64/arm_base64.cpp
tests/base64_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/520

fix for issue 520

---

fuzz/conversion.cpp

The current conversion fuzzer uses C++ index sequences for expansion. While this was great fun developing, it is a problem when getting a stack trace since the function names are *very* long (4 kB).
I simplified this to using an array of function pointers instead.
The speed increased because I made the array static, but the same thing would have helped the code before this change as well.

simplify the conversion fuzzer to get smaller function signatures

---

fuzz/CMakeLists.txt
fuzz/README.md
fuzz/misc.cpp

This fuzzer runs clean on x86.

add misc fuzzer for functions not covered elsewhere

---

CMakeLists.txt
Doxyfile
README.md
fuzz/CMakeLists.txt
fuzz/README.md
fuzz/misc.cpp
include/simdutf/simdutf_version.h
src/haswell/avx2_convert_utf8_to_utf16.cpp
src/westmere/sse_convert_utf8_to_utf16.cpp

release 5.3.8

---

src/rvv/rvv_validate.inl.cpp
tests/convert_utf16le_to_utf32_with_errors_tests.cpp
tests/convert_utf32_to_utf16be_tests.cpp
tests/validate_utf32_with_errors_tests.cpp

fixes https://github.com/simdutf/simdutf/issues/531

fixing issue 531

---

src/rvv/rvv_utf16_to.inl.cpp

fixes https://github.com/simdutf/simdutf/issues/532

fixing issue 532

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

Fixes https://github.com/simdutf/simdutf/issues/544

version 5.3.11 (release candidate)

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

fixes https://github.com/simdutf/simdutf/issues/544

version 5.3.13 (release candidate)

---

include/simdutf/compiler_check.h

add compiler detection for C++20 and C++23

---

fuzz/misc.cpp

I wonder if there is anything more than could be asserted than I already do? See in particular line 153.

extend the misc fuzzer to cover convert_latin1_to_utf8_safe()

---

README.md
include/simdutf/implementation.h
src/arm64/arm_base64.cpp
src/fallback/implementation.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/scalar/base64.h
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

More work on PR https://github.com/simdutf/simdutf/pull/571
It adds more tests and some fixes (hopefully).
We need even more tests, I believe.

more testing... for Adding last chunk handling options

---

fuzz/base64.cpp
include/simdutf/implementation.h
src/arm64/arm_base64.cpp
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/avx2_base64.cpp
src/haswell/implementation.cpp
src/icelake/icelake_base64.inl.cpp
src/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/scalar/base64.h
src/simdutf/fallback/implementation.h
src/westmere/implementation.cpp
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

clang format for issue 440

---

src/icelake/icelake_base64.inl.cpp

For inputs of smaller lengths like <64 bytes, the icelake implementation of base64 encode calls the scalar function to process. This functionality is implemented in this PR which saves some clock cycles for small input encoding.
Before the change, running the base64 benchmark on 48 byte input:
```
memcpy                                   :   2.81 GB/s  16.34 GHz   5.82 c/b   5.21 i/b   0.90 i/c
libbase64                                :   1.10 GB/s   9.65 GHz   8.80 c/b  24.52 i/b   2.79 i/c
simdutf::icelake                         :   1.45 GB/s  11.07 GHz   7.62 c/b  16.67 i/b   2.19 i/c
simdutf::haswell                         :   1.87 GB/s  12.67 GHz   6.79 c/b  12.33 i/b   1.82 i/c
simdutf::westmere                        :   2.08 GB/s  13.55 GHz   6.52 c/b  10.44 i/b   1.60 i/c …
```

Optimize the tail base64 encode for Icelake

---

src/arm64/arm_base64.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/implementation.cpp
src/scalar/base64.h
src/westmere/sse_base64.cpp
tests/base64_tests.cpp
tests/helpers/test.h

This PR improves our tests by changing the default implementation. It also solves one more issue with partial chunks.

Better handling partial last chunk + slightly better tests

---

src/arm64/arm_base64.cpp
src/arm64/implementation.cpp
src/haswell/avx2_base64.cpp
src/haswell/implementation.cpp
src/icelake/icelake_base64.inl.cpp
src/icelake/implementation.cpp
src/lasx/implementation.cpp
src/lasx/lasx_base64.cpp
src/lsx/implementation.cpp
src/lsx/lsx_base64.cpp
src/westmere/implementation.cpp
src/westmere/sse_base64.cpp

Making ignore_garbage as a template variable instead of runtime variable

---

src/scalar/base64.h

Fixes https://github.com/simdutf/simdutf/issues/607

Optimize base64 tail decoding

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

Patch release for issue identified by @pauldreik

release candidate 5.7.1

---

src/implementation.cpp
src/scalar/utf16.h

Relates to https://github.com/simdutf/simdutf/issues/581

avoids some unnecessary casts

---

tests/validate_utf16le_basic_tests.cpp
tests/validate_utf16le_with_errors_tests.cpp

Related to https://github.com/simdutf/simdutf/issues/581

removing some unnecessary casts

---

src/icelake/implementation.cpp

Implementing #528 for Icelake.
Read the data only once and maintain the bodies of UTF8, UTF16LE and UTF32LE checker inlined inside the routine and feed each 64 byte input block once.
The UTF16LE routine is slightly modified to avoid checks and separately maintain the high surrogate ending state. All unit tests for detect_encodings seems to be passing.
Still this probably needs more careful review and I'm not sure if mathematically it is correct at the moment. Not sure about the speed-up either.
If this design and implementation is good, then separately the rest of x86 can be updated.

Optimize AVX512 detect_encodings implementation

---

include/simdutf/portability.h

@pauldreik The current simdutf release will break on old Apple system. :-/

We need to check for old Apple systems.

---

CMakeLists.txt
Doxyfile
README.md
include/simdutf/simdutf_version.h

This release candidate is meant to fix an issue recently found and fixed by @WojciechMula : https://github.com/simdutf/simdutf/pull/642

release candidate

---

tests/convert_utf8_to_latin1_with_errors_tests.cpp

this replaces MR https://github.com/simdutf/simdutf/pull/636 which had a minor issue.

add test for issue 633

---

scripts/clang_format.sh
scripts/clang_format_docker.sh

I suspect that @WojciechMula had trouble with clang-format recently. Let us make our scripts nicer.

This makes the formatting script more robust

---

singleheader/amalgamate.py

Group code into procedures and introduce main()

Refactor amalgamate.py

---

singleheader/amalgamate.py

fixes https://github.com/simdutf/simdutf/issues/656
I think that even though @clausecker does not speak Python, he will understand this PR.

making the amalgamation script more robust

---

.github/workflows/aarch64.yml
.github/workflows/armv7.yml
.github/workflows/ppc64le.yml
.github/workflows/s390x.yml

My current theory is that it is down to a bad Linux distribution.

let us try to fix the CI failures with uraimo/run-on-arch-actio

---

tests/convert_utf32_to_utf16be_with_errors_tests.cpp

One of our tests assumes that we are under a little endian system.
Fixes https://github.com/simdutf/simdutf/issues/666

fixing a test (issue 666)

---

src/arm64/implementation.cpp
src/haswell/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/ppc64/implementation.cpp
src/westmere/implementation.cpp

As the title states - remove a template not used anywhere

Drop unused template

---

scripts/benchmark_print.py
scripts/new.txt
scripts/old.txt

Update `scripts/benchmark_print.py` to parse the current output from benchmark utility. Extended also a script to compare two benchmark results (output from the script got used in #674).

Update benchmark script

---

benchmarks/base64/benchmark_base64.cpp

Let decide which implementations have to be benchmarked. The default behaviour remains --- all known implementations are executed when no extra option is present.
I wanted to benchmark only our implementations and it was impossible without recompiling the benchmarking tool. I refactored it to accept option `-f implementation` and `-l` to list implementations. It's now possible to use the tool in the following way:
```shell
$  ./benchmark_base64 -d ../../../../base64data/email/enron8.txt -f haswell
[...]
simdutf::haswell                         :  15.18 GB/s  6.15 %   4.38 GHz   0.29 c/b   1.21 i/b   4.21 i/c 
simdutf::haswell (accept garbage)        :  16.91 GB/s  6.62 %   4.33 GHz   0.26 c/b   1.00 i/b   3.92 i/c 
$ ./benchmark_base64 -l
roundtrip:
* simdutf::haswell
* simdutf::westmere …
```

benchmarks/base64: allow to filter implementations

---

include/simdutf/internal/isadetection.h

Fix namespaced header include for loongarch (issue 690)

---

benchmarks/benchmark.cpp
benchmarks/src/benchmark.cpp
benchmarks/src/benchmark.h
benchmarks/src/cmdline.cpp
benchmarks/src/cmdline.h
src/haswell/avx2_convert_utf32_to_utf16.cpp
src/westmere/sse_convert_utf32_to_utf16.cpp

Kernels: Westmere & Haswell. Since we're handling surrogates in scalar code, there's no point in calculating exact surrogate position bitmasks. This brings some performance improvement.
Extend also benchmark utility to better handle command line arguments, and added benchmarks for conversions into UTF-16BE.
Benchmarks:
```
$ cat list 
convert_utf32_to_utf16be+haswell
convert_utf32_to_utf16be+westmere
convert_utf32_to_utf16be_with_errors+haswell
convert_utf32_to_utf16be_with_errors+westmere
convert_utf32_to_utf16le+haswell
convert_utf32_to_utf16le+westmere
convert_utf32_to_utf16le_with_errors+haswell
convert_utf32_to_utf16le_with_errors+westmere
convert_valid_utf32_to_utf16be+haswell
convert_valid_utf32_to_utf16be+westmere
convert_valid_utf32_to_utf16le+haswell …
```

[x86] targets: simplify UTF-32 to UTF-16

---

src/arm64/arm_base64.cpp

The vectorized path processes in multiple of 48 bytes and scalar encode is done for <48 bytes.
This PR adds vectorized encode path using 8-byte NEON instructions if >=24 bytes are available for the tail. Only upto 23 bytes therefore are encoded using scalar function.
This should help with improving the speed for encode size which have >24 bytes leftover (1/2 probability assuming random distribution of `srclen % 48`).

arm64: optimize base64 24-byte tail encode using NEON

---

src/arm64/arm_base64.cpp

Adapts the westmere's translation logic for delta_hash by using bits 7:3 instead of bits 7:4 for hi_nibble previously.
New lookup table is designed so that when lo & hi is done, it results in error bytes being mapped to 0. 
Spaces are mapped to 1.
Since hi is obtained by TBL of hi_bits 7:4, it results in hi = 0 for all input bytes > 127 with MSB set.
This makes the base64 decode logic symmetrical for base64 and base64url. 
Thus the extra logic to handle '_' is not not required and decode should be faster for base64url inputs.

arm64: alternate base64 decode logic to optimize base64url decode

---

scripts/base64/neon_generate_lut.py

Based on suggestion from @WojciechMula, adding the script that prints the lut_lo and lut_hi for the various variants.

Add the python script to generate the LUT used in NEON

---

include/simdutf/implementation.h
src/implementation.cpp
tests/base64_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/751

Adding Relaxed write version for base64_to_binary_safe

---

src/rvv/rvv_utf32_to.inl.cpp

While calling fully validating conversion routine is not a logic error, conversion of already validated inputs is supposed to be faster than validating conversion routines.
Extracted UTF-32 to UTF-8 into a template and make validation a compile-time constant.

RVV: faster valid UTF-32 to UTF-8

---

src/implementation.cpp
tests/atomic_base64_tests.cpp

@pauldreik did find one more bug... this should fix it. Reproducing test case added.
fixes https://github.com/simdutf/simdutf/issues/763

fixes issue 763

---

src/rvv/rvv_utf32_to.inl.cpp

Perform fewer error checking in the case of input values that fit in 16 bits.

rvv: faster UTF-32 to UTF-16

---

scripts/check_feature_macros.py
singleheader/amalgamation_demo.cpp
src/rvv/implementation.cpp
src/simdutf/ppc64/implementation.h
tests/CMakeLists.txt
tools/CMakeLists.txt

adding tests to check feature macros

---

benchmarks/CMakeLists.txt
benchmarks/benchmark_to_well_formed_utf16.cpp
cmake/CPM.cmake
tools/CMakeLists.txt

adding a nice to_well_formed benchmark

---

.github/workflows/loongarch64-gcc-14.2.yml

uses qemu-v10.0.2 to test the LSX and LASX.

add qemu to test LoongArch64

---

.github/workflows/msys2-clang.yml
src/scalar/utf16.h
tests/readme_tests.cpp

Fixes https://github.com/simdutf/simdutf/issues/829

fixing issue 829
