simdutf/simdutf

src/scalar/utf8.h

If the 8 + 8 bytes ASCII check is unsuccessful, then there is no reason
to repeat it until the non-ASCII byte is found.

Skip ASCII check until the non ASCII byte is found

---

LICENSE-MIT

Also break lines at 80 characters.

Add missing copyright line to MIT license

---

include/simdutf.h
include/simdutf/compiler_check.h
include/simdutf/implementation.h

Use non-atomic pointer for dynamic dispatch when atomic is not available

---

src/generic/utf8_to_utf32/valid_utf8_to_utf32.h
tests/convert_valid_utf8_to_utf32_tests.cpp

Fix #132. There is an issue when using `convert_valid_utf8_to_utf32` related to a non-ASCII character following a long chain of ASCII characters. Credit to @KaiserLancelot for identifying the bug.

Fix issue #132.

---

src/icelake/implementation.cpp

Fix #107 
Implements functions from #107 except UTF-16LE validation (I think @clausecker has that part). Also adds utf32_length_from_utf8 and utf32_length_from utf16 (same as count_utf8 and count_utf16 respectively) as well as utf8_length_from_utf32 and utf16_length_from_utf32. Nothing differs significantly from haswell and westmere implementations.

AVX-512 miscellaneous functions 

---

src/arm64/arm_validate_utf16le.cpp
src/simdutf/arm64/simd.h

Closes #136
Before:
```
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
testcases: 1
input detected as UTF16 little-endian
current system detected as arm64
===========================
validate_utf16+arm64, input size: 65542, iterations: 10000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
kpc_set_config failed, run the program with sudo
1.873 GB/s (7.2 %)    0.936 Gc/s     2.00 byte/char 
validate_utf16+fallback, input size: 65542, iterations: 10000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
2.579 GB/s (3.4 %)    1.289 Gc/s     2.00 byte/char 
```
After:
```
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point …
```

Optimize ARM utf16 validation

---

src/icelake/icelake-from-utf8.inl.cpp
src/icelake/icelake-from-valid-utf8.inl.cpp
src/icelake/icelake-macros.inl.cpp
src/icelake/icelake-utf8-common.inl.cpp

In this PR (to be applied to https://github.com/simdutf/simdutf/pull/97), we add a few more branches to help the performance of some Asian inputs. The net result is a slight loss of performance all around, with a nice gain in the few cases where our haswell kernel was slower. This might prove to be an interesting compromise since with this new code, the icelake kernel is always faster than haswell, except maybe on emoji inputs. 
The gist of the idea is to check when our expanded 512-bit registers contain too few valid characters and to merge two successive expanded 512-bit registers when we detect such a scenario. When this branch is not taken, we pay for some arithmetic and a branch not taken. However, when the branch is fruitful, the gains are interesting:  from   3.3 GB/s to 3.9 GB/s …

Making the AVX-512 UTF-8 to UTF-16 transcoder more branchy

---

src/icelake/icelake-convert-utf16-to-utf32.inl.cpp
src/icelake/implementation.cpp
tests/helpers/transcode_test_base.h

Fix #129
The algorithm offers a vectorized approach in the presence of surrogate pairs instead of the scalar fallback that we have for other architectures. For surrogates, the idea is to have a register that is shifted by one 16-bit word to the right to align high surrogate words with low surrogate words. We expand all words to 32-bit words of both registers (shifted and non-shifted registers). Then, we shift the bits of the low surrogates by 10 to the left in the non-shifted register, add both registers together and add a constant (0xfca04200, credits to @clausecker) to remove surrogates prefixes and to add the plane shift 0x10000. 
With AVX-512, this is not too hard to do with all the masked instructions and _mm512_mask_compressstoreu_epi32. I might have used too many masked …

AVX-512 UTF-16 to UTF-32

---

src/arm64/arm_convert_utf16_to_utf8.cpp

Current `simdutf` failes the tests on aarch64 environments like below:
```
96% tests passed, 2 tests failed out of 48
Total Test time (real) =  30.80 sec
The following tests FAILED:
24 - convert_utf16be_to_utf8_tests (Subprocess aborted)
34 - convert_valid_utf16be_to_utf8_tests (Subprocess aborted)
```
This PR fixes this.

Fix Buffer Overrun on aarch64

---

src/icelake/icelake_convert_utf16_to_utf8.inl.cpp
src/icelake/implementation.cpp
src/simdutf/icelake.h
src/simdutf/icelake/intrinsics.h
tests/convert_utf16_to_utf32_tests.cpp
tests/convert_utf16_to_utf8_tests.cpp

This PR integrates Robert's transcoder. The results are excellent. The new transcoder is 50% faster than the haswell (previous best) transcoder on non-trivial inputs. Importantly, it transcodes emojis at full speed.
```
For each file, the first numbers are for the new transcoder (icelake), and the second one is the existing transcoder (haswell).
../unicode_lipsum/wikipedia_mars/arabic.utf16.txt
15.988 GB/s (2.8 %)    7.994 Gc/s     2.00 byte/char 
10.356 GB/s (1.3 %)    5.178 Gc/s     2.00 byte/char 
../unicode_lipsum/wikipedia_mars/chinese.utf16.txt
14.184 GB/s (1.2 %)    7.092 Gc/s     2.00 byte/char 
9.980 GB/s (1.3 %)    4.990 Gc/s     2.00 byte/char 
../unicode_lipsum/wikipedia_mars/czech.utf16.txt
22.842 GB/s (1.8 %)   11.421 Gc/s     2.00 byte/char 
12.955 GB/s (1.0 %)    6.477 …
```

Fast UTF-16 to UTF-8 transcoder (AVX-512)

---

src/icelake/icelake_convert_utf16_to_utf8.inl.cpp

This fixes the performance of the template function `utf16_to_utf8_avx512i` under LLVM. The function is now strictly faster than the AVX2 counterpart. LLVM has trouble generating good mask-related code and `utf16_to_utf8_avx512i` does a lot of work in 'mask space'.

Fixes issue 176.

---

CMakeLists.txt

Allow skipping the build of the tools subdir, like it is done for the benchmarks.
This is useful when one just wants to build the static library and does not have a working or only a broken iconv installed. 
Otherwise the build fails with an error from building sutf:
```
:> cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=C:\code\img -DBUILD_TESTING=OFF -DSIMDUTF_BENCHMARKS=OFF C:\Users\msc\AppData\Local\Temp\VC19\amd64\debug\simdutf-2.0.2
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile …
```

Allow skipping the build of the tools via SIMDUTF_TOOLS=OFF

---

benchmarks/src/benchmark.cpp
tools/sutf.cpp

There is a version of iconv under windows called win-iconv. Unfortunately, it has a non-standard function signature:
```c++
size_t iconv(iconv_t cd, WINICONV_CONST char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
```
To accommodate it, we can branch on the existence of the macro WINICONV_CONST  at compile-time. It makes the code somewhat uglier, but it should make compilation more robust.
This relates to issue https://github.com/simdutf/simdutf/pull/178

Guarding calls to iconv to accommodate win-iconv

---

src/simdutf/icelake/intrinsics.h

Node.js releases were failing due to the changes pushed for GCC-8. This make sure that avx512f is supported before applying the changes.
Fixes https://github.com/simdutf/simdutf/issues/186

fix: check for avx512 before applying gcc-8 changes

---

.github/workflows/msys2-clang.yml
.github/workflows/msys2.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu22.yml
.github/workflows/ubuntu22_gcc12.yml
include/simdutf/portability.h
src/icelake/icelake_convert_utf16_to_utf8.inl.cpp
src/icelake/icelake_from_utf8.inl.cpp
src/simdutf/fallback/bitmanipulation.h
src/simdutf/haswell/begin.h
src/simdutf/haswell/end.h
src/simdutf/haswell/intrinsics.h
src/simdutf/icelake/begin.h
src/simdutf/icelake/end.h
src/simdutf/icelake/intrinsics.h
src/simdutf/westmere/intrinsics.h

The standard x86intrin.h header generates some warning under recent versions of GCC. Not our fault. But we can silence the warnings.

This PR attempts to silence some spurious GCC warnings (unrelated to our code).

---

src/icelake/icelake_utf8_common.inl.cpp
src/simdutf/icelake/intrinsics.h

Hi. I am creating a simdutf conan package.
I have encountered a compilation error in gcc9 debug build.
Strangely enough, only gcc9 debug builds seem to have the compilation errors that occur with gcc8.
```
.../src/icelake/icelake_utf8_common.inl.cpp:446:12: error: the last argument must be an 8-bit immediate
446 |     return _mm512_alignr_epi8(input, rotated, 16-N);
|            ^~~~~~~~~~~~~~~~~~
```
original: https://c3i.jfrog.io/c3i/misc/logs/pr/13829/6-linux-gcc/simdutf/2.0.2//9cb7ac99f58a79b591516cbdd53096db4a815c86-build.txt
Now the patch is provided on the conan package side, but since it seems to be an independent issue, could you please adopt it for simdutf?

fix compilation error on gcc 9 debug build

---

benchmarks/src/benchmark_base.cpp

We compute incorrectly these metrics.

Correcting cycle-per-byte and cycle-per-char metrics.

---

README.md
include/simdutf/error.h
src/generic/utf8_to_utf16/utf8_to_utf16.h
src/generic/utf8_to_utf32/utf8_to_utf32.h
src/icelake/icelake_from_utf8.inl.cpp
src/icelake/implementation.cpp
src/scalar/utf8_to_utf16/utf8_to_utf16.h
src/scalar/utf8_to_utf32/utf8_to_utf32.h
tests/basic_fuzzer.cpp
tests/convert_utf8_to_utf16be_with_errors_tests.cpp
tests/convert_utf8_to_utf16le_with_errors_tests.cpp
tests/convert_utf8_to_utf32_with_errors_tests.cpp

For short strings,`convert_utf8_to_utf16le_with_errors` may sometimes cause buffer overflows by reading before the buffer when the input is not UTF-8.
It is a rather silly bug, and it was easily fixed. It is disappointing that our fuzzer did not catch this: I have therefore extended it. We are now doing more testing over (small) garbage inputs.
Credit to @Jarred-Sumner and his team.
Fixes https://github.com/simdutf/simdutf/issues/213

Fixing issue 213

---

.github/workflows/msys2.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu20sani.yml
.github/workflows/ubuntu20single.yml
.github/workflows/ubuntu22.yml
.github/workflows/ubuntu22_gcc12.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml

relates to https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

chore: remove `[skip ci]` handling as it is natively supported

---

fuzz/build.sh
fuzz/roundtrip.cc

This PR adds a simple roundtrip fuzz harness, which is a modified version of the example in the readme. I've got a corresponding draft PR open for continuous fuzzing at https://github.com/google/oss-fuzz/pull/9942.

feat(fuzz): Adds a roundtrip fuzz harness

---

src/arm64/arm_convert_utf8_to_utf16.cpp
src/arm64/arm_convert_utf8_to_utf32.cpp
src/arm64/implementation.cpp
src/simdutf/arm64/simd.h

* [ARM64] Faster NEON UTF-8 conversion routines
- Tune the algorithm for NEON instead of a 1:1 SSE4 conversion
- Make use of NEON's compound shifts and bitwise selection - Clang needs a hack to avoid constant propagation :(
- NEON has a byteswap instruction, use it (applies to other funcs too but I'm focusing here for now)
- Make use of half vectors when appropriate
- Handle 4 byte sequences better. Some of these can be applied to SSE4.
- Add a fast path for 3-4 4-byte sequences, it is worth it.
- Calculate surrogates in parallel and skip the intermediate UTF-32
- Simplify selection logic
- Use one magic addition to clear the UTF-8 prefix, adjust the surrogate offset, and add the surrogate prefixes
- Note that this can be applied to SSE as well, but it needs some tweaks.
* More tweaks, …

[NEON] Faster UTF-8 conversion routines (#241)

---

tools/sutf.cpp

When compiling with MSVC targeting x86, the compiler issues a warning when building `sutf`. Thanks to https://github.com/simdutf/simdutf/pull/266, this warning even gets promoted to an error, which means you currently can't build `sutf` for x86 Windows with MSVC. I know that simdutf is heavily optimitzed for 64-Bit platforms, so using it on x86 is somewhat discouraged, but I assume the code should still at least be buildable.
I tested this with Visual Studio 2022, but I assume previous versions of the compiler also issue this warning.

Fix warning about signed/unsigned mismatch on x86 Windows

---

src/icelake/icelake_convert_latin1_to_utf8.inl.cpp
src/icelake/implementation.cpp

These are the benchmarks for this PR: 
convert_latin1_to_utf8+haswell, input size: 440052, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin8.txt
5.440 ins/byte,    1.842 cycle/byte,    1.734 GB/s (1.7 %),     3.193 GHz,    2.954 ins/cycle 
5.440 ins/char,    1.842 cycle/char,    1.734 Gc/s (1.7 %)     1.00 byte/char 
convert_latin1_to_utf8+icelake, input size: 440052, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin8.txt
0.437 ins/byte,    0.170 cycle/byte,   18.199 GB/s (1.4 %),     3.100 GHz,    2.564 ins/cycle 
0.437 ins/char,    0.170 cycle/char,   18.199 Gc/s (1.4 %)     1.00 byte/char 
convert_latin1_to_utf8+iconv, input size: 440052, iterations: 30000, dataset: …

AVX512 latin1 to utf8

---

src/scalar/utf16.h
src/scalar/utf32.h

This is a small PR that ensures that some of our fallback functions are easier to autovectorize.
credit: @ttsugriy for the idea

More autovectorizing code in the fallback functions.

---

README.md
include/simdutf/implementation.h
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/generic/utf8_to_latin1/utf8_to_latin1.h
src/generic/utf8_to_latin1/valid_utf8_to_latin1.h
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/scalar/utf8.h
src/scalar/utf8_to_latin1/utf8_to_latin1.h
src/simdutf/arm64/implementation.h
src/simdutf/fallback/implementation.h
src/simdutf/haswell/implementation.h
src/simdutf/icelake/implementation.h
src/simdutf/westmere/implementation.h
src/simdutf/westmere/simd.h
src/simdutf/westmere/simd16-inl.h
src/westmere/implementation.cpp
src/westmere/sse_convert_utf8_to_latin1.cpp
tests/convert_utf8_to_latin1_tests.cpp
tests/random_fuzzer.cpp
tests/special_tests.cpp

This is a version with minor fixes from https://github.com/simdutf/simdutf/pull/263 by @Nick-Nuon 
It adds new tests. Furthermore, the latin1_length_from_utf8 is already accelerated: it is just the count function, so I did that.
Fix https://github.com/simdutf/simdutf/issues/292

UTF 8 => Latin (Westmere/SSE)

---

benchmarks/src/apple_arm_events.h
src/arm64/arm_convert_utf8_to_latin1.cpp
src/arm64/implementation.cpp

On Apple M2 (LLVM 14) with the `french.utflatin8.txt` file.
```
$ sudo ./benchmarks/benchmark -P convert_utf8_to_latin1 -F ../unicode_lipsum/wikipedia_mars/french.utflatin8.txt
Password:
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 73.2
Using iconv version 267
testcases: 1
input detected as UTF8
current system detected as arm64
===========================
convert_utf8_to_latin1+arm64, input size: 440052, iterations: 30000, dataset: ../unicode_lipsum/wikipedia_mars/french.utflatin8.txt
1.864 ins/byte,    1.005 cycle/byte,    3.420 GB/s (9.8 %),     3.439 GHz,    1.854 ins/cycle 
1.897 ins/char,    1.023 cycle/char,    3.360 Gc/s (9.8 %)     1.02 byte/char …
```

UTF-8 to Latin 1 (ARM)

---

benchmarks/src/benchmark.cpp
src/arm64/arm_convert_utf16_to_latin1.cpp
src/arm64/arm_convert_utf16_to_utf32.cpp
src/arm64/arm_convert_utf16_to_utf8.cpp
src/arm64/arm_convert_utf32_to_latin1.cpp
src/arm64/arm_convert_utf32_to_utf16.cpp
src/arm64/arm_convert_utf32_to_utf8.cpp
src/arm64/arm_validate_utf16.cpp
src/arm64/implementation.cpp
src/simdutf/arm64/simd16-inl.h
src/westmere/sse_convert_utf16_to_utf32.cpp

LLVM 14/Apple M2
UTF-32 to Latin 1
```
convert_utf32_to_latin1+arm64, input size: 1729220, iterations: 3000, dataset: unicode_lipsum/wikipedia_mars/french.utflatin32.txt
0.446 ins/byte,    0.061 cycle/byte,   58.290 GB/s (1.2 %),     3.549 GHz,    7.323 ins/cycle 
1.784 ins/char,    0.244 cycle/char,   14.572 Gc/s (1.2 %)     4.00 byte/char 
convert_utf32_to_latin1+iconv, input size: 1729220, iterations: 3000, dataset: unicode_lipsum/wikipedia_mars/french.utflatin32.txt
13.008 ins/byte,    2.089 cycle/byte,    1.634 GB/s (6.0 %),     3.413 GHz,    6.227 ins/cycle 
52.034 ins/char,    8.356 cycle/char,    0.408 Gc/s (6.0 %)     4.00 byte/char 
convert_utf32_to_latin1+icu, input size: 1729220, iterations: 3000, dataset: unicode_lipsum/wikipedia_mars/french.utflatin32.txt
16.655 ins/byte, …
```

This introduces fast UTF16/UTF32 to Latin 1 to our arm kernel

---

src/westmere/implementation.cpp
src/westmere/sse_convert_latin1_to_utf8.cpp

It is not possible for SSE to be used on a big endian system.

SSE is always little endian: removing unnecessary code path

---

src/westmere/implementation.cpp
src/westmere/sse_convert_utf16_to_latin1.cpp

EDIT: Benchmarks for lastest commits: 
```
convert_utf16_to_latin1+haswell, input size: 864610, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin16.txt
0.345 ins/byte,    0.407 cycle/byte,    7.853 GB/s (1.3 %),     3.198 GHz,    0.848 ins/cycle 
0.345 ins/char,    0.407 cycle/char,    7.853 Gc/s (1.3 %)     1.00 byte/char 
convert_utf16_to_latin1+icelake, input size: 864610, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin16.txt
0.143 ins/byte,    0.448 cycle/byte,    6.909 GB/s (1.2 %),     3.097 GHz,    0.318 ins/cycle 
0.143 ins/char,    0.448 cycle/char,    6.909 Gc/s (1.2 %)     1.00 byte/char 
convert_utf16_to_latin1+iconv, input size: 864610, iterations: 30000, dataset: …
```

SSE UTF16 => latin1

---

src/haswell/avx2_convert_latin1_to_utf8.cpp
src/haswell/implementation.cpp

This PR implements avx2_convert_latin1_to_utf8: fixes https://github.com/simdutf/simdutf/issues/282
The speed is essentially the same as @aspic-fish's Westmere implementation. See https://github.com/simdutf/simdutf/pull/298/files
GCC 12, Ice Lake processor, French.latin1 file:
```
convert_latin1_to_utf8+haswell, input size: 432305, iterations: 30000, dataset: ../unicode_lipsum/wikipedia_mars/french.latin1.txt
1.249 ins/byte,    0.545 cycle/byte,    5.861 GB/s (4.4 %),     3.195 GHz,    2.291 ins/cycle 
1.249 ins/char,    0.545 cycle/char,    5.861 Gc/s (4.4 %)     1.00 byte/char 
convert_latin1_to_utf8+westmere, input size: 432305, iterations: 30000, dataset: ../unicode_lipsum/wikipedia_mars/french.latin1.txt
1.430 ins/byte,    0.571 cycle/byte,    5.597 GB/s (12.9 %),     3.195 GHz, …
```

Latin 1 => UTF-8 (haswell kernel)

---

include/simdutf/encoding_types.h
src/icelake/icelake_convert_latin1_to_utf16.inl.cpp
src/icelake/icelake_convert_utf16_to_latin1.inl.cpp
src/icelake/implementation.cpp

The performance is decent and the implementation is relatively clean.
Ice Lake processor, GCC12... french data files...
```
$ ./build/benchmarks/benchmark -P convert_latin1_to_utf16 -F unicode_lipsum/wikipedia_mars/french.latin1.txt  -I 6000
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 67.1
testcases: 1
input detected as unknown
current system detected as icelake
===========================
convert_latin1_to_utf16+haswell, input size: 432305, iterations: 6000, dataset: unicode_lipsum/wikipedia_mars/french.latin1.txt
0.282 ins/byte,    0.206 cycle/byte,   15.534 GB/s (3.5 %),     3.203 GHz,    1.367 ins/cycle 
0.282 ins/char,    0.206 cycle/char,   15.534 Gc/s …
```

UTF-16 <=> Latin 1, icelake kernel

---

src/arm64/arm_convert_latin1_to_utf16.cpp
src/arm64/arm_convert_latin1_to_utf32.cpp
src/arm64/arm_convert_latin1_to_utf8.cpp
src/arm64/implementation.cpp

This PR provides fast function (with ARM NEON) for Latin 1 transcoding to Unicode formats.
Here are some benchmarks on an M2 processor with LLVM 14. I use the french.latin1 file from the wikipedia mars dataset.
The performance is good.
```
$ ./benchmarks/benchmark -P convert_latin1_to_utf8 -F ../unicode_lipsum/wikipedia_mars/french.latin1.txt -I 3000
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 73.2
Using iconv version 267
testcases: 1
input detected as unknown
current system detected as arm64
===========================
convert_latin1_to_utf8+arm64, input size: 432305, iterations: 3000, dataset: ../unicode_lipsum/wikipedia_mars/french.latin1.txt
6.963 GB/s (3.4 …
```

Implementing fast Latin1 to UTF functions for ARM.

---

src/icelake/icelake_convert_utf32_to_latin1.inl.cpp
src/icelake/implementation.cpp

It is difficult to get performance benefits because we are basically bounded by the size of the loads. Nevertheless, the AVX-512 code is elegant.

This implements UTF-32 to Latin1 using the icelake kernel.

---

src/generic/utf8.h

I benchmarked @alantudyk 's suggestion
These are the benchmarks I got: 
on big 1 for gcc 11.3.1:
```
//gcc 11.3.1 Before
/* count_utf8+haswell, input size: 446908, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utf8.txt
0.220 ins/byte,    0.070 cycle/byte,   45.771 GB/s (36.7 %),     3.210 GHz,    3.131 ins/cycle 
0.226 ins/char,    0.072 cycle/char,   44.538 Gc/s (36.7 %)     1.03 byte/char 
WARNING: Measurements are noisy, try increasing iteration count (-I).
count_utf8+icelake, input size: 446908, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utf8.txt
0.083 ins/byte,    0.048 cycle/byte,   65.376 GB/s (11.8 %),     3.116 GHz,    1.746 ins/cycle 
0.086 ins/char,    0.049 cycle/char,   63.614 Gc/s (11.8 %)     1.03 byte/char …
```

count_code_points change

---

src/haswell/avx2_convert_utf16_to_latin1.cpp
src/haswell/implementation.cpp

These are my benchmarks for this PR:
```
convert_utf16_to_latin1+haswell, input size: 864610, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin16.txt
0.438 ins/byte,    0.133 cycle/byte,   24.034 GB/s (1.2 %),     3.199 GHz,    3.291 ins/cycle 
0.876 ins/char,    0.266 cycle/char,   12.017 Gc/s (1.2 %)     2.00 byte/char 
convert_utf16_to_latin1+icelake, input size: 864610, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin16.txt
0.172 ins/byte,    0.103 cycle/byte,   30.166 GB/s (1.7 %),     3.101 GHz,    1.675 ins/cycle 
0.344 ins/char,    0.206 cycle/char,   15.083 Gc/s (1.7 %)     2.00 byte/char 
convert_utf16_to_latin1+iconv, input size: 864610, iterations: 30000, dataset: …
```

AVX2 UTF16 => Latin1

---

src/westmere/implementation.cpp
src/westmere/sse_convert_latin1_to_utf16.cpp

Wanted to work a bit on SSE latin1 => Utf16 to compare apple to apple as much as possible. Looks like it gives more or less the speeds. 
Coming back to the other PR later on today
```
convert_latin1_to_utf16+haswell, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
0.282 ins/byte,    0.207 cycle/byte,   15.456 GB/s (3.1 %),     3.202 GHz,    1.361 ins/cycle 
0.282 ins/char,    0.207 cycle/char,   15.456 Gc/s (3.1 %)     1.00 byte/char 
convert_latin1_to_utf16+icelake, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
0.157 ins/byte,    0.214 cycle/byte,   14.472 GB/s (2.3 %),     3.103 GHz,    0.731 ins/cycle 
0.157 ins/char,    0.214 cycle/char,   14.472 Gc/s (2.3 %) …
```

SSE Latin1 => UTF16

---

README.md
include/simdutf/implementation.h
src/arm64/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/westmere/implementation.cpp
src/westmere/sse_convert_latin1_to_utf16.cpp

While @Nick-Nuon is busy finishing up https://github.com/simdutf/simdutf/pull/325, this PR is meant to clean up some tasks.
Fixes https://github.com/simdutf/simdutf/issues/244

finishing touch on Latin 1 functions

---

benchmarks/dataset/scripts/utf8type.py

The `utf8type.py` script currently doesn't behave as expected, and reports the wrong character counts:
```bash
$ ./scripts/utf8type.py wikipedia_mars/chinese.txt
two bytes
ASCII: 0  2-Bytes: 0  3-Bytes: 95328 4-Bytes: 0
ASCII: 0.0%  2-Bytes: 0.0%  3-Bytes: 100.0% 4-Bytes: 0.0%
```
after the patch:
```bash
$ ./scripts/utf8type.py wikipedia_mars/chinese.txt
three bytes
ASCII: 32751  2-Bytes: 507  3-Bytes: 20521 4-Bytes: 0
ASCII: 34.35611782477341%  2-Bytes: 0.5318479355488419%  3-Bytes: 21.526728768042968% 4-Bytes: 0.0%
```
The output might be a bit confusing as the percentages don't add up to 100%, since it uses the percentage of total bytes used by the character types.
To get the percentage of characters that have a specific length, `l = len(array)` could be changed to `l = sum(counts)`, …

fix utf8type.py

---

src/westmere/sse_convert_utf32_to_latin1.cpp

Performance note: the unpack instructions are very fast (1 latency, high throughput). So many machines can do the two unpack in one cycle, and then the second unpack immediately after. Then we store the result. Having fewer stores is beneficial. And it happens to solve build problems with GCC8.
Fixes https://github.com/simdutf/simdutf/issues/337
cc @anonrig

Fixing issue 337: rewrite of sse_convert_utf32_to_latin1 (simplify)

---

src/simdutf/haswell/simd.h
src/simdutf/haswell/simd16-inl.h

NUM_CHUNKS can only be 2, but we are accessing
indexes outside of this range i.e. 2,3.

bug: Fix out of bounds access for haswell simd op

---

.github/workflows/vs16-ci.yml
.github/workflows/vs17-ci-cxx20.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml

This should also speed up CI generally.

The basic_fuzzer test times out too often when running the tests in debug mode under windows.

---

CMakeLists.txt
Doxyfile
include/simdutf/simdutf_version.h
src/arm64/arm_convert_utf32_to_utf16.cpp

This adds a potentially missing cast (`vreinterpret`) in two locations to account for some compilers that require it.
This was observed by @anonrig (thanks).
This should become directly a third patch release on the 4.0 series.

Add vreinterpret

---

.github/workflows/macos-latest.yml
.github/workflows/ubuntu22sani.yml
README.md
include/simdutf/implementation.h
src/implementation.cpp
src/scalar/utf16.h
src/scalar/utf8.h
tests/helpers/test.h
tests/readme_tests.cpp

If you take a UTF-8 (or UTF-16) input and consider an arbitrary prefix, the end of the prefix might contain a partial character.  You can simply roll back to the previous complete character, and decode without error. In the next iteration, you include the truncated content with the rest of the string.
You can thus decode a UTF-8 string piece by piece:
```cpp
const char unicode[] = "\xc3\xa9\x63ole d'\xc3\xa9t\xc3\xa9";
// suppose you want to decode only the start of this string.
size_t length = 10;
// Picking 10 bytes is problematic because we might end up in the middle of a
// code point. But we can rewind to the previous code point.
length = simdutf::trim_partial_utf8(unicode, length);
// Now we can transcode safely
size_t budget_utf16 = simdutf::utf16_length_from_utf8(unicode, length); …
```

provide convenience functions to trim partial characters at the end of a string.

---

src/arm64/arm_convert_latin1_to_utf8.cpp
src/arm64/arm_convert_utf16_to_utf8.cpp
src/arm64/arm_convert_utf32_to_utf8.cpp
src/arm64/implementation.cpp
src/simdutf/arm64/simd.h
src/simdutf/arm64/simd16-inl.h

This PR replaces a function-based workaround for Visual Studio ARM constant initialization with a macro-based approach. The macro approach might lead to more efficient code for ARM-based Visual Studio builds. Other systems are unaffected.

Using macro workaround for Visual Studio ARM

---

src/error.cpp
src/generic/utf8_to_latin1/valid_utf8_to_latin1.h
src/icelake/implementation.cpp
src/westmere/internal/write_v_u16_11bits_to_utf8.cpp
src/westmere/sse_convert_latin1_to_utf8.cpp

A few more warnings were reported:
https://github.com/nodejs/node/pull/50930#issuecomment-1835032160
Note that all but one of these warnings have to do with C++98 compatibility but `simdutf` requires C++11 or better. 
cc @anonrig

Silencing some more warnings.

---

.github/workflows/aarch64.yml
.github/workflows/alpine.yml
.github/workflows/armv7.yml
.github/workflows/debian.yml
.github/workflows/documentation.yml
.github/workflows/macos-latest.yml
.github/workflows/msys2-clang.yml
.github/workflows/msys2.yml
.github/workflows/s390x.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu20sani.yml
.github/workflows/ubuntu20single.yml
.github/workflows/ubuntu22-cxx20.yml
.github/workflows/ubuntu22.yml
.github/workflows/ubuntu22_gcc12.yml
.github/workflows/ubuntu22sani.yml
.github/workflows/vs16-ci.yml
.github/workflows/vs17-arm-ci.yml
.github/workflows/vs17-ci-cxx20.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml

This updates [actions/checkout](https://github.com/actions/checkout) to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20

Update actions/checkout in GitHub Actions to v4

---

src/haswell/implementation.cpp
src/ppc64/implementation.cpp
src/westmere/implementation.cpp

Credit @Validark
Test results... GCC 12, Icelake, Arabic-Lipsum.utf8.txt 
I am getting a 2% to 4% gain. By itself, this may not be statistically meaningful, but we see the instruction count going down by about the same amount which tells us (with high confidence) that it is an actual optimization.
Before:
```
validate_utf8+haswell, input size: 81685, iterations: 20000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
1.113 ins/byte,    0.319 cycle/byte,   10.081 GB/s (0.5 %),     3.213 GHz,    3.493 ins/cycle 
1.987 ins/char,    0.569 cycle/char,    5.648 Gc/s (0.5 %)     1.78 byte/char 
validate_utf8+westmere, input size: 81685, iterations: 20000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
2.426 ins/byte,    0.492 cycle/byte,    6.514 GB/s (2.8 %),     3.206 GHz,    4.931 …
```

We can improve slightly UTF-8 validation under some x64 targets.

---

src/implementation.cpp

This should slightly reduce the function call overhead on systems where runtime dispatching is not needed. Note that this overhead was already small so it may not translate into easily measurable gains.

disables runtime dispatching when there is a single implementation.

---

src/arm64/arm_convert_utf32_to_utf8.cpp
tests/convert_utf32_to_utf8_tests.cpp
tests/convert_utf32_to_utf8_with_errors_tests.cpp

Fixing overflow in UTF32 to UTF8 under Neon.

---

tests/convert_utf8_to_utf16be_tests.cpp
tests/convert_utf8_to_utf16le_tests.cpp
tests/convert_valid_utf8_to_utf16be_tests.cpp
tests/convert_valid_utf8_to_utf16le_tests.cpp
tests/validate_utf8_basic_tests.cpp
tests/validate_utf8_with_errors_tests.cpp

The copyright sign (bytes 0xC2, 0xA9) in UTF-8 should transcode in UTF-16 to 0x00, 0xA9 or 0xA9, 0x00 depending on the endianness. In particular, the copyright sign (bytes 0xC2, 0xA9) should be detected as valid UTF-8.

adding copyright sign tests

---

src/rvv/rvv_utf8_to.inl.cpp
src/rvv/rvv_validate.inl.cpp
tests/convert_utf8_to_utf16le_tests.cpp
tests/validate_utf8_brute_force_tests.cpp

Thanks to @OMaghiarIMGs [comment](https://github.com/simdutf/simdutf/pull/373#discussion_r1529993897), I looked over the rvv utf8 validation code again, and found a bug in it.
The ASCII fast path must make sure that the next three bytes are valid.
An easy way to do that is to check if they are also ASCII, this is what this patch does.
An alternative would be to subtract three from `vl`, but then you would need to avoid the possibility of such code turning into an infinite loop, when `vl<=3`. The first fix seemed more straight forward.
I also cleaned up the `tail` variable. It was used for three separate things, and two of those could've used a smaller value.

fix rvv utf8 validation bug

---

README.md
benchmarks/CMakeLists.txt
include/simdutf/implementation.h
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/scalar/base64.h
src/simdutf/arm64/implementation.h
src/simdutf/fallback/implementation.h
src/simdutf/haswell/implementation.h
src/simdutf/icelake/implementation.h
src/simdutf/ppc64/implementation.h
src/simdutf/rvv/implementation.h
src/simdutf/westmere/implementation.h
src/westmere/implementation.cpp
tests/base64_tests.cpp

Though base64url allows padding characters, they are most commonly omitted by default. This PR adopts the common default.

fix: base64url should omit padding by default

---

include/simdutf/internal/isadetection.h
include/simdutf/portability.h

This PR solves compilation errors when building for the [Windows ARM64EC ABI](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/).
You can repro in an [ARM64 Visual Studio Developer Command Prompt](https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio/#developer-command-prompt):
```
>cl /nologo /c /EHsc /std:c++17 /arm64EC simdutf.cpp
simdutf.cpp : error C7303: AVX512 types (__m512) are not currently supported in ARM64EC code
simdutf.cpp : error C7303: AVX512 types (__m512) are not currently supported in ARM64EC code
simdutf.cpp : error C7303: AVX512 types (__m512) are not currently supported in ARM64EC code
simdutf.cpp : error C7303: AVX512 types (__m512) are not currently supported in …
```

add Windows ARM64EC support

---

src/scalar/utf8_to_latin1/utf8_to_latin1.h

Remove unnecessary include in a header file.

Drop reference to std::cout and friends

---

tests/reference/validate_utf8.cpp

There is a bug in a our test framework which was exposed by recent changes by @WojciechMula 
Note that this is not a bug in the library itself.

fix: validate_utf8 in our tests

---

.github/workflows/vs17-arm-ci.yml

This PR adds an ARM64EC architecture CI build workflow to windows-vs17. See [here](https://github.com/jblazquez/simdutf/actions/runs/8610077872/job/23595020847) for an example of a passing CI run. I had to switch the vs17-arm-ci builds to [target the Windows 11 SDK](https://stackoverflow.com/a/77651884) because ARM64EC is Windows 11 only.
It's not currently possible (as far as I know) to actually run Windows ARM tests in CI, so - as before - the Windows ARM CI workflows are build-only.
Note that support for ARM64EC was [added in CMake 3.20.0 and improved in 3.23.0](https://gitlab.kitware.com/cmake/cmake/-/issues/21724). The minimum version of CMake declared in the CMakeLists.txt file is [3.15.0](https://github.com/simdutf/simdutf/blob/d12bb58/CMakeLists.txt#L1). I'm not sure if we need to …

add Windows ARM64EC CI workflow

---

tests/detect_encodings_tests.cpp

The encoding tests are currently too strict which can trigger false errors.

fix detect encodings

---

tests/detect_encodings_tests.cpp

When testing encoding detection, make sure the generated data does not start with a BOM marker.

test: fix detect_encodings_tests

---

benchmarks/base64/benchmark_base64.cpp
src/arm64/arm_base64.cpp

This looks like a Visual Studio bug. The function `vld4q_u8` should take a `uint8_t*` pointer, not a `char*` pointer. I did not investigate further and I just fix the issue by casting when under Visual Studio.
Fixes https://github.com/simdutf/simdutf/issues/407

fix: problems building Windows ARM on some platforms

---

src/simdutf/arm64/simd16-inl.h
src/simdutf/haswell/simd16-inl.h
src/simdutf/westmere/simd16-inl.h

PR #421 fix some warning with GCC14 using c++20 mode, but some still need a fixes (see #424)

fix: satisfying gcc14 compiler warning again (#424)

---

benchmarks/base64/benchmark_base64.cpp
benchmarks/base64/openssl3_base64.h

This adds the current OpenSSL 3.3.x implementation to the benchmarks. Please feel free to resolve if this doesn't belong to simdutf benchmarks.
Sample execution on an Intel Cascade Lake CPU, which is detected as Haswell, because Cascade Lake does not support AVX512 VBMI2 and VPOPCNTDQ instructions.
```
./benchmark_base64 -d one.pem
memcpy                                   :  67.47 GB/s   9.35 GHz   0.14 c/b   0.20 i/b   1.41 i/c 
openssl3.3.x                             :   0.33 GB/s   4.46 GHz  13.40 c/b  37.06 i/b   2.77 i/c 
libbase64_space_decode                   :   0.82 GB/s   4.49 GHz   5.47 c/b  15.51 i/b   2.84 i/c 
node                                     :   1.47 GB/s   4.58 GHz   3.12 c/b  12.69 i/b   4.07 i/c 
simdutf::haswell                         :   6.41 GB/s   4.99 GHz …
```

Add OpenSSL 3.3.x base64 decoder to benchmarks.

---

README.md
include/simdutf/implementation.h
src/haswell/avx2_base64.cpp
src/haswell/implementation.cpp
src/scalar/base64.h
src/westmere/implementation.cpp
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

By default, we use padding except for the URL variant where we do not. However, some users of the library might need other variations: the conventional base64 without padding *or* the URL variant with padding. This PR provides this functionality.
I also give more of an explanation as to why we have the padding conventions we do. They come from RFC 4648.
cc @constellation

fix: add more variants to base64

---

src/scalar/utf16_to_latin1/utf16_to_latin1.h

This fixes sending a nullptr to memcpy, which is undefined behaviour. It also prevents doing pointer arithmetics on a nullptr in the return statement.
The existing test "random_fuzzer" covers this.

prevent invoking memcpy on nullptr in utf16_to_lat1::convert

---

README.md
include/simdutf/implementation.h

`convert_valid_*_to_latin1` assumes that the input is valid and can be directly converted to Latin1.
Fix https://github.com/simdutf/simdutf/issues/466 and https://github.com/simdutf/simdutf/issues/464

documenting issue 464

---

tests/convert_utf16be_to_utf8_tests.cpp
tests/convert_utf16be_to_utf8_with_errors_tests.cpp

While validating #469 I saw that ub sanitizer with gcc complains about unaligned load. 
This fixes the problem. clang does not complain.
Is there no CI job that runs gcc with sanitizers that has caught this?
I could not use the latest master because of the newly tweaked inline in 04b9b9ed1a698a161c71a6f901041735f19cd93b:
> pauldreik@privat-kodning:~/code/delaktig/simdutf/tests/blah-gcc$ ninja && ctest -j100
> [74/165] Building CXX object src/CMakeFiles/simdutf.dir/simdutf.cpp.o
> FAILED: src/CMakeFiles/simdutf.dir/simdutf.cpp.o 
> /usr/lib/ccache/g++-12  -I/home/pauldreik/code/delaktig/simdutf/src -I/home/pauldreik/code/delaktig/simdutf/include -g -std=c++11 -Wall -Wextra -Weffc++ -Wfatal-errors -Wsign-compare -Wshadow -Wwrite-strings -Wpointer-arith -Winit-self -Wconversion …

fix alignment error in unit tests (gcc complains)

---

src/haswell/avx2_validate_utf16.cpp
src/haswell/avx2_validate_utf32le.cpp
src/icelake/implementation.cpp
src/westmere/sse_validate_utf16.cpp
src/westmere/sse_validate_utf32le.cpp
tests/null_safety_tests.cpp

This is a PR for discussion.
Current master does not go through the tests clean with UB sanitizer. I fixed the places reported by the sanitizer in this PR. That does not mean there is no UB left. 
I ran the benchmarks and it seems to be a bit slower but the noise is big - is there some way to do A/B-testing with the benchmark and see the difference compared to the noise?
I used
`benchmarks/benchmark -F unicode_lipsum/lipsum/*.utf8.txt -P validate_utf8+icelake -I 100000 `
and it gives say 0.3 % difference (very noisy) on the first file (Arabic).
openssl has a special "pedantic" mode so it is possible to fuzz or use other tools on the library. I am not convinced that is a good idea for simdutf. Perhaps just fixing the issues reported by the sanitizer is enough, given that performance does …

guard against nullptr arithmetic

---

src/arm64/implementation.cpp

There are probably more places that need this but I just fixed those that showed up when I fuzzed.

add length check for arm where UB sanitizer finds nullptr arithmetic

---

src/scalar/utf32_to_latin1/valid_utf32_to_latin1.h
tests/convert_valid_utf32_to_latin1_tests.cpp

the other implementations check for out of range values before converting them to latin1.
the scalar implementation skipped over such invalid values unless the input length was odd, in which case the last value is converted anyway.

make convert_valid_utf32_to_latin1 scalar correct and consistent

---

include/simdutf/common_defs.h
include/simdutf/implementation.h

These assume that the user knows that the function will succeed. It does not do any validation. If the input is invalid (cannot be converted to latin1), the result is undetermined and may include crashes.
This PR will deprecate them formally.

The convert_valid_*_to_latin1 were never documented in our README and they should not be considered part of our public API. 

---

benchmarks/src/benchmark_base.h
cmake/simdutf-flags.cmake
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/westmere/implementation.cpp

Using this UTF8 short file:
https://github.com/lemire/unicode_lipsum/tree/main/short
Run the benchmark...
```
benchmark -P utf8_length_from_latin1 -F fourbytes.utf8.txt -I 1000000
```
GCC 12, Intel Ice Lake:
```
utf8_length_from_latin1+fallback, input size: 64, iterations: 100000, dataset: shorter.txt
1.281 ins/byte,    0.266 cycle/byte,   11.825 GB/s (16.2 %),     3.141 GHz,    4.824 ins/cycle 
5.125 ins/char,    1.062 cycle/char,    2.956 Gc/s (16.2 %)     4.00 byte/char      5.4 ns
WARNING: Measurements are noisy, try increasing iteration count (-I).
utf8_length_from_latin1+haswell, input size: 64, iterations: 100000, dataset: shorter.txt
0.672 ins/byte,    0.219 cycle/byte,   14.493 GB/s (14.2 %),     3.170 GHz,    3.071 ins/cycle 
2.688 ins/char,    0.875 cycle/char,    3.623 Gc/s …
```

optimize utf8_length_from_latin1 for short strings

---

.github/workflows/cifuzz.yml

There are warnings in CI.
Trying to get rid of them by following https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

ci: update codeql action to v3

---

fuzz/build.sh

this is a workaround for build problems on oss fuzz due to an old version of clang being used for arm64.
arm64 is not officially supported by oss-fuzz yet. if we can get at least one fuzzer running on arm64 there, it is a win.

fix oss fuzz build failure on arm64

---

README.md
include/simdutf/implementation.h
src/fallback/implementation.cpp
src/implementation.cpp
src/scalar/latin1_to_utf8/latin1_to_utf8.h
src/simdutf/rvv/implementation.h
tests/convert_latin1_to_utf8_tests.cpp

This is an alternative PR to @ronag's PR  (who should be fully credited for the work) at https://github.com/simdutf/simdutf/pull/554
It is basically @ronag's code with 
1. A *proposed* name change... the suffix `_s` is replaced by `_safe`.
2. A simplification: we do not include the new function in the kernels, instead we use @ronag's algorithm on top of existing fast functions.
3. It adds a sanity test.

Convert latin1 to utf8 safe

---

include/simdutf/implementation.h
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/simdutf/arm64/implementation.h
src/simdutf/fallback/implementation.h
src/simdutf/haswell/implementation.h
src/simdutf/icelake/implementation.h
src/simdutf/ppc64/implementation.h
src/simdutf/rvv/implementation.h
src/simdutf/westmere/implementation.h
src/westmere/implementation.cpp

(This is a PR for yagiz/add-validate-base64, merging this would not affect the main branch.)
If we add a function to our kernels, we have to add it everywhere. Obviously, this makes little to no sense if we are not going also to optimize it for the different kernels (e.g., write an ARM implementation).
Note that this function is not super difficult to optimize as the base64 decoding routines already do the validation. Furthermore, they do with options (base64url, and so forth). We could reuse much of the existing code.
Importantly: this will not work if you are trying to validate a base64 string that was percent encoded. So we should clarify the motivation. It can be interesting to decode quickly a base64 string that was percent encoded, but this function won't help much for that.
On this …

completing the implementation a bit

---

include/simdutf/implementation.h
tests/base64_tests.cpp

This PR hopefully fixes a C++11 build issue.
Further, I think that we might have a standard interpretation issue. The handling of the chunk is currently done in a function that is called after we have removed the padding characters ('='), so it is not aware of the padding characters. (We should be able to pass the information if it is needed.)
I added some tests from WebKit. Maybe more could be added.
I expect this PR to current fail in CI, that's normal.

further work on issue 440

---

.gitignore
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/westmere/sse_base64.cpp

The to_base64_mask function computes the 64 bit mask and spaces variable which contains the information about error location within the 64 byte block. Thus by counting the trailing zeros, the first error byte can be detected rather than looping and doing scalar operations.

Replace while loop with efficient tzcnt for checking error

---

fuzz/base64.cpp

the input from libfuzzer is overaligned. stepping an even number of option bytes into the fuzzing data before potentially casting it to char16 makes it properly aligned.
without this fix, UBSAN fails deep down in std::vector.

fix data alignment in base64 fuzzer

---

.github/workflows/loongarch64-gcc-14.2.yml

There may be problems with qemu testing LSX and LASX. After fixing these problems, we will start testing the LoongArch64 architecture.
PATCH Reference: https://github.com/simdjson/simdjson/pull/2160

Add LoongArch64 CI(only build)

---

src/icelake/icelake_base64.inl.cpp

Optimize the base64 decode AVX512 routine for <64 bytes input and use Masked AVX512 instructions to process most of the <64 bytes tail.
Before the change:
```
current system detected as icelake.
memcpy                                   :   3.74 GB/s  17.75 GHz   4.75 c/b   4.15 i/b   0.87 i/c
libbase64                                :   1.98 GB/s  12.10 GHz   6.10 c/b  13.55 i/b   2.22 i/c
libbase64_space_decode                   :   1.03 GB/s   8.98 GHz   8.71 c/b  19.48 i/b   2.24 i/c
openssl3.3.x                             :   0.60 GB/s   7.58 GHz  12.63 c/b  45.42 i/b   3.60 i/c
node                                     :   1.65 GB/s  10.99 GHz   6.68 c/b  16.45 i/b   2.46 i/c
simdutf::icelake                         :   1.59 GB/s  10.17 GHz   6.40 c/b  12.62 i/b   1.97 i/c …
```

Optimize base64 decode AVX512 kernel for small input sizes

---

include/simdutf/implementation.h
src/arm64/arm_base64.cpp
src/fallback/implementation.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/lasx/lasx_base64.cpp
src/lsx/lsx_base64.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/scalar/base64.h
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

Adds the functionality described in #585 
Includes the unit tests written in #600 and the extra couple lines of fixes described there.
The tests are passing locally (on x86_64), rest architectures might need fixes if failures are detected.

Adding the base64 decode with garbage option code changes

---

src/scalar/base64.h

GCC 12, Intel Ice Lake
```
$  ./build/benchmarks/base64/benchmark_base64 -d ../base64data/dns/*.txt
memcpy                                   :  21.68 GB/s   2.61 GHz   0.12 c/b   0.21 i/b   1.73 i/c
libbase64_space_decode                   :   1.06 GB/s   3.19 GHz   2.99 c/b  14.72 i/b   4.92 i/c
openssl3.3.x                             :   0.40 GB/s   3.19 GHz   7.95 c/b  37.67 i/b   4.74 i/c
node                                     :   1.24 GB/s   3.19 GHz   2.58 c/b  13.02 i/b   5.05 i/c
simdutf::icelake                         :   8.39 GB/s   3.09 GHz   0.37 c/b   1.17 i/b   3.18 i/c
simdutf::icelake (accept garbage)        :  10.09 GB/s   3.09 GHz   0.31 c/b   0.85 i/b   2.78 i/c
simdutf::haswell                         :   4.38 GB/s   3.19 GHz   0.73 c/b   3.27 i/b   4.49 i/c …
```

adding guards for LLVM optimization

---

src/icelake/icelake_base64.inl.cpp
tests/base64_tests.cpp

Previously submitted change #593 causes Icelake base64 decode routine to return `INVALID_BASE64_CHARACTER` for `strict` chunk option case, which is not what the other routines return due to `base64_tail_decode`.
This has been reported in #615 by @pauldreik.
Adding the reported test and the new code change to address this behavior for Icelake base64 decode routine.
Icelake routines have the `base64_tail_decode` inlined inside the `bufferptr - buffer != 0` block above which handles most of the cases. This change adds the extra check for `strict` and `stop_with_partial` with padding scenario which should match all other implementations as well.

Fixing icelake base64 decode behavior to be similar to other routines

---

tests/base64_tests.cpp
tests/basic_fuzzer.cpp
tests/convert_latin1_to_utf16be_tests.cpp
tests/convert_latin1_to_utf16le_tests.cpp
tests/convert_latin1_to_utf32_tests.cpp
tests/convert_utf16be_to_latin1_tests.cpp
tests/convert_utf16be_to_latin1_tests_with_errors.cpp
tests/convert_utf16le_to_latin1_tests.cpp
tests/convert_utf16le_to_latin1_tests_with_errors.cpp
tests/convert_utf32_to_utf16be_with_errors_tests.cpp
tests/convert_utf8_to_latin1_with_errors_tests.cpp
tests/convert_utf8_to_utf16be_with_errors_tests.cpp
tests/convert_utf8_to_utf16le_with_errors_tests.cpp
tests/convert_utf8_to_utf32_with_errors_tests.cpp
tests/convert_valid_utf16be_to_latin1_tests.cpp
tests/convert_valid_utf16le_to_latin1_tests.cpp
tests/convert_valid_utf32_to_latin1_tests.cpp
tests/detect_encodings_tests.cpp
tests/helpers/test.h
tests/random_fuzzer.cpp
tests/validate_ascii_basic_tests.cpp
tests/validate_ascii_with_errors_tests.cpp
tests/validate_utf8_with_errors_tests.cpp

I noticed when building with -Wall -Wextra that the tests contain code that trigger warnings.
There is one particularly interesting warning where I am not sure about the fix, see 0b2559a54dac2f5f04104c584904246a8a901357

fix some compiler warnings

---

tests/validate_utf16be_basic_tests.cpp
tests/validate_utf16be_with_errors_tests.cpp
tests/validate_utf16le_basic_tests.cpp
tests/validate_utf16le_with_errors_tests.cpp
tests/validate_utf32_basic_tests.cpp
tests/validate_utf32_with_errors_tests.cpp

using __ anywhere in an identifier is reserved for use by the implementation.

fix illegal names using double underscores

---

src/icelake/icelake_utf32_validation.inl.cpp
src/icelake/implementation.cpp
tests/validate_utf32_basic_tests.cpp

Modified the `validate_utf32` function to avoid using scalar loop for tail processing and to obtain the result using masked AVX512 instructions. Seems to speed up small inputs as observed below:
Before the changes:
```
validate_utf32+icelake, input size: 48, iterations: 1000, dataset: temp
2.521 ins/byte,    0.542 cycle/byte,   10.139 GB/s (15.1 %),     5.492 GHz,    4.654 ins/cycle
11.000 ins/char,    2.364 cycle/char,    2.323 Gc/s (15.1 %)     4.36 byte/char      4.7 ns
```
After the changes:
```
validate_utf32+icelake, input size: 48, iterations: 1000, dataset: temp
1.333 ins/byte,    0.271 cycle/byte,   20.357 GB/s (1.8 %),     5.513 GHz,    4.923 ins/cycle
5.818 ins/char,    1.182 cycle/char,    4.665 Gc/s (1.8 %)     4.36 byte/char      2.4 ns
```

Optimize icelake validate_utf32 for small inputs using masked AVX512 instructions

---

src/arm64/arm_base64.cpp
src/fallback/implementation.cpp
src/haswell/avx2_base64.cpp
src/icelake/icelake_base64.inl.cpp
src/lasx/lasx_base64.cpp
src/lsx/lsx_base64.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/westmere/sse_base64.cpp
tests/base64_tests.cpp

Related to #619 
With these changes the routines return the same error code and don't change based on location of spaces.

Making the base64 decode return value consistent

---

src/icelake/implementation.cpp

Replace the sequence of extract + add with `_mm512_reduce_add_epi64` intrinsic. https://godbolt.org/z/G1xbdqGKK
This leads to better code generated for GCC and MSVC, clang is able to optimize the current code and won't benefit as can be checked in the compiler explorer.

Replace extract and add sequence with _mm512_reduce_add_epi64 

---

fuzz/README.md
fuzz/build.sh
fuzz/helpers/common.h
fuzz/random_fuzz.sh

This adds a helper script for running fuzzing - the existing one which is for oss-fuzz.sh is somewhat hard coded to debian.
The new one makes more effort to find a working clang installation. I tested it on freebsd, rocky linux and debian so far.
It also randomizes the optimization flags, which is useful to trigger different behaviour.

fuzzing improvements

---

fuzz/roundtrip.cpp
tests/random_fuzzer.cpp

Some our tests cast char* pointers to char16_t* or char32_t* pointers without checking the alignment. This can trigger undefined behaviour. Let us be more careful.

fix with random fuzzers for alignment issues

---

tests/convert_utf8_to_utf16be_with_errors_tests.cpp

I found this by running on the freebsd arm64 system (thanks @clausecker !)
It also reproduces on debian arm64.
this is the error output on freebsd:
```
Running 'issue XXXX'... =================================================================
==62362==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x507000000068 at pc 0x0000003b06e8 bp 0xffffffffcf20 sp 0xffffffffcf18
WRITE of size 2 at 0x507000000068 thread T0
#0 0x3b06e4 in unsigned long simdutf::arm64::(anonymous namespace)::convert_masked_utf8_to_utf16<(simdutf::endianness)1>(char const*, unsigned long, char16_t*&) /home/pauldreik/code/simdutf/src/arm64/arm_convert_utf8_to_utf16.cpp
#1 0x37bcd8 in unsigned long simdutf::arm64::(anonymous namespace)::utf8_to_utf16::validating_transcoder::convert<(simdutf::endianness)1>(char …
```

add test case for buffer write overflow in convert_utf8_to_utf16be (arm64)

---

README.md
fuzz/misc.cpp
include/simdutf/implementation.h
tests/CMakeLists.txt
tests/span_tests.cpp

This adds a span based api in addition to the existing.
The original idea was to use std::span, but instead a templated attempt is used, constrained by concepts. (credit: @WojciechMula )
This makes the user's code pretty nice - it is possible to use std::string, std::string_view, std::vector, std::array, std::span etc . Also user supplied types with .data() and .size() will work.
It is also possible to let users use char/unsigned char/std::byte/std::uint8_t/std::int8_t, all is allowed. This is because C++ allows those types to alias anything. The same story is not true for uint16_t and char16_t.
closes: https://github.com/simdutf/simdutf/issues/557

add span based API #557

---

README.md
include/simdutf/common_defs.h
include/simdutf/implementation.h
include/simdutf/portability.h
src/icelake/implementation.cpp
tests/base64_tests.cpp
tests/span_tests.cpp
tests/validate_utf16be_with_errors_tests.cpp
tests/validate_utf16le_with_errors_tests.cpp

This adds checking for concept and span support as suggested in https://github.com/simdutf/simdutf/pull/558#pullrequestreview-2530799530 .
I also took the liberty of
- move include of `<tuple>` to where it is used.
- get rid of unused macros SIMDUTF_BEGIN_DEBUG_BLOCK etc.
- remove include of `<cassert>` since it was not used
- fix minor issues in README.md

Span API followup

---

src/icelake/implementation.cpp

This is to fix build error when we set use_libcxx_modules=true in [chromium build](https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8726426032921605025/+/u/compile/raw_io.output_text_failure_summary_).

Add missing include headers for `std::pair`

---

fuzz/README.md
fuzz/random_fuzz.sh

The important thing is that I with help from @camel-cdr  got fuzzing to work for riscv inside qemu.
It also speeds up the fuzzing by downloading the backup corpus from oss-fuzz instead of starting from zero.
I have run this on riscv inside qemu for about 50 cpu hours per simd width of 128, 256 and 1024. Nothing found!

Improve random fuzzer script

---

fuzz/README.md
src/rvv/rvv_utf8_to.inl.cpp
tests/convert_valid_utf8_to_utf16le_tests.cpp

Note, this is preliminary!
This adds a test which exposes a problem on riscv, when run with the rvv_vl_half_avl=on flag passed to qemu. the entire cpu flag is `-cpu 'rv64,v=on,zvbb=on,vlen=256,rvv_ta_all_1s=on,rvv_ma_all_1s=on,rvv_vl_half_avl=on'`
When trying to recreate the fuzzer finding, I ran into unit tests failing:
```
root@debian:~/code/simdutf/build# tests/convert_valid_utf8_to_utf16le_tests 
Checking implementation rvv
Running 'issue xxx'...  OK
Running 'convert pure ASCII'... .................................................................................................... OK
Running 'convert 1 or 2 UTF8 bytes'... .................................................................................................... OK
Running 'convert 1 or 2 or 3 UTF8 bytes'... …
```

Add test for fuzzer finding on riscv using rvv_vl_half_avl=on

---

src/icelake/icelake_convert_latin1_to_utf32.inl.cpp
src/icelake/implementation.cpp
tests/convert_latin1_to_utf32_tests.cpp

Compute the final chunk using masked AVX512 instructions.
Add unit test for varying lengths instead of just fixed length 256 to cover the last block.

Optimize icelake latin1 to utf32 for small inputs using masked AVX512 instructions

---

src/arm64/implementation.cpp
src/generic/ascii_validation.h
src/generic/utf8_validation/utf8_validator.h
src/haswell/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/westmere/implementation.cpp

This is just a technical change required by #637 (selective amalgamation). For instance, if we want just ASCII & UTF-16 support, there's no need to include UTF-8 stuff.

Extract ASCII validation into a separate file

---

src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/generic/utf16.h
src/generic/utf8.h
src/generic/utf8_to_latin1/utf8_to_latin1.h
src/generic/utf8_to_latin1/valid_utf8_to_latin1.h
src/generic/utf8_to_utf16/utf8_to_utf16.h
src/generic/utf8_to_utf16/valid_utf8_to_utf16.h
src/generic/utf8_to_utf32/utf8_to_utf32.h
src/generic/utf8_to_utf32/valid_utf8_to_utf32.h
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/simdutf.cpp

Per our comment, include scalar/* files exactly once. Before including these files, include implementation headers, thanks to that we may disable/enable certain common code onwards.

Sort out including scalar/* files

---

include/simdutf/implementation.h
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/rvv/rvv_length_from.inl.cpp
src/scalar/latin1.h
src/scalar/utf16.h
src/scalar/utf32.h
src/simdutf/arm64/implementation.h
src/simdutf/fallback/implementation.h
src/simdutf/haswell/implementation.h
src/simdutf/icelake/implementation.h
src/simdutf/lasx/implementation.h
src/simdutf/lsx/implementation.h
src/simdutf/rvv/implementation.h
src/simdutf/westmere/implementation.h
src/westmere/implementation.cpp

All these methods simply return the length of input string, as we don't check for a BOM marker.

Simplify calculating length latin1 <=> UTF16/UTF32

---

src/lasx/implementation.cpp
src/lasx/lasx_convert_latin1_to_utf16.cpp
src/lasx/lasx_convert_latin1_to_utf32.cpp
src/lasx/lasx_convert_latin1_to_utf8.cpp
src/lasx/lasx_convert_utf16_to_latin1.cpp
src/lasx/lasx_convert_utf16_to_utf32.cpp
src/lasx/lasx_convert_utf16_to_utf8.cpp
src/lasx/lasx_convert_utf32_to_latin1.cpp
src/lasx/lasx_convert_utf32_to_utf16.cpp
src/lasx/lasx_convert_utf32_to_utf8.cpp
src/lasx/lasx_convert_utf8_to_utf16.cpp
src/lasx/lasx_convert_utf8_to_utf32.cpp
src/lasx/lasx_validate_utf16.cpp
src/lsx/implementation.cpp
src/lsx/lsx_convert_latin1_to_utf16.cpp
src/lsx/lsx_convert_latin1_to_utf32.cpp
src/lsx/lsx_convert_latin1_to_utf8.cpp
src/lsx/lsx_convert_utf16_to_latin1.cpp
src/lsx/lsx_convert_utf16_to_utf32.cpp
src/lsx/lsx_convert_utf16_to_utf8.cpp
src/lsx/lsx_convert_utf32_to_latin1.cpp
src/lsx/lsx_convert_utf32_to_utf16.cpp
src/lsx/lsx_convert_utf32_to_utf8.cpp
src/lsx/lsx_convert_utf8_to_utf16.cpp
src/lsx/lsx_convert_utf8_to_utf32.cpp
src/lsx/lsx_validate_utf16.cpp

* loongarch64: fix lsx and lasx nullptr tests in fuzz testing
Ref: PR-469
* loongarch64: fix lsx and lasx issue_631
* loongarch64: fixed vbitsel usage error

Fix fuzz test failure in lsx and lasx

---

src/icelake/icelake_convert_utf32_to_utf16.inl.cpp
src/icelake/implementation.cpp

1) Upgrade the 256 and 128 bit intrinsics to 512 and 256 respectively, effectively processing 2x data per intrinsic.
2) Replace the scalar loop for handling high and low surrogate pair with masked AVX512 instructions.
3) Replace the last tail chunk processing using scalar loop with masked AVX512 instructions.

Optimized icelake AVX512 for utf32 to utf16 conversion

---

README.md
include/simdutf/implementation.h
src/implementation.cpp

We have some silly (convenience) functions which may have gone missing. This PR puts them back or add them if they weren't there. These functions are truly silly and could have been omitted, but we include them purely for convenience.
I am also adding a terminating comment, moving from
```C++
#endif
```
to
```C++
#endif // SIMDUTF_SPAN
```
in some places as it is more readable to know what the `#endif` is closing.
Fixes https://github.com/simdutf/simdutf/issues/661

fixes for Issue 661

---

src/icelake/icelake_convert_utf32_to_utf16.inl.cpp
src/icelake/implementation.cpp
src/simdutf/haswell/intrinsics.h
tests/convert_utf32_to_utf16be_with_errors_tests.cpp

Same logic as done in #648 for the `utf32_to_utf16_with_errors` function for AVX512.
Only extra logic added is that if error occurs, then the partial output chunk also needs to be written.

Optimized icelake AVX512 for utf32_to_utf16_with_errors

---

singleheader/amalgamate.py

I detected this when generating the singleheader.zip file for 6.2.0
the ceiling directory needs to be one ABOVE the git root.

fix mistake in git ceiling dir for amalgamation script

---

include/simdutf/implementation.h
src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/icelake/implementation.cpp
src/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/ppc64/implementation.cpp
src/rvv/implementation.cpp
src/simdutf/arm64/implementation.h
src/simdutf/fallback/implementation.h
src/simdutf/haswell/implementation.h
src/simdutf/icelake/implementation.h
src/simdutf/lasx/implementation.h
src/simdutf/lsx/implementation.h
src/simdutf/ppc64/implementation.h
src/simdutf/rvv/implementation.h
src/simdutf/westmere/implementation.h
src/westmere/implementation.cpp

Methods `maximal_binary_length_from_base64` and `base64_length_from_binary` do not depend on the target, make them regular methods of base class `implementation`.

Simplify base64 implementation

---

src/icelake/icelake_convert_utf32_to_utf16.inl.cpp
src/icelake/icelake_utf8_common.inl.cpp

[We recently upgraded the UTF-32 to UTF-16 conversion functions in the icelake kernel](https://github.com/simdutf/simdutf/commit/123ddb7344886a35ab33d13c5643e98ad99d3267). Specifically, [Shreesh Adiga](https://github.com/tantei3) did (@tantei3). The code is fine for Intel processors... and if you just read it out, it great work. Unfortunately, we used `_mm512_mask_compressstoreu_epi16` which is a big issue. Under AMD processors, this can compile down to code that it is very slow. Effectively, AMD Zen 4 does not support it and they microcoded some hack.
If I knew how, I'd make it impossible to use this intrinsic in the future.

Fixing AVX-512 performance bug

---

src/haswell/avx2_convert_latin1_to_utf16.cpp
src/haswell/avx2_convert_utf16_to_latin1.cpp
src/haswell/avx2_convert_utf32_to_latin1.cpp

Early draft, it's faster on my Zen3, need more benchmarking on Skylake and Icelake.
Commands to test:
```
#!/bin/sh
./benchmark -P convert_latin1_to_utf16+haswell -F unicode_lipsum/wikipedia_mars/*.latin1.*
./benchmark -P convert_utf16_to_latin1+haswell -F unicode_lipsum/wikipedia_mars/*.utflatin16.*
./benchmark -P convert_utf16_to_latin1_with_errors+haswell -F unicode_lipsum/wikipedia_mars/*.utflatin16.*
./benchmark -P convert_valid_utf16_to_latin1+haswell -F unicode_lipsum/wikipedia_mars/*.utflatin16.*
./benchmark -P convert_utf32_to_latin1+haswell -F unicode_lipsum/wikipedia_mars/*.utflatin32.*
./benchmark -P convert_valid_utf32_to_latin1+haswell -F unicode_lipsum/wikipedia_mars/*.utflatin32.*
./benchmark -P convert_utf32_to_latin1_with_errors+haswell -F …
```

AVX2: better Latin1 <=> UTF-16 conversion

---

scripts/base64bench_print.py
scripts/benchmark_print.py
src/CMakeLists.txt
src/haswell/avx2_base64.cpp
src/westmere/sse_base64.cpp

It's often that the whole block of input contains only one "bad" character. To compress such a simple case, a specialised procedure was introduced for *Westemre* and *Haswell* targets.
Performance results for command `./benchmark_base64 -f simdutf -d base64data/email/*` (https://github.com/lemire/base64data)
```
+------------------------------------------------------------------------+
|               decoding of 1976492 bytes from 15 input(s)               |
+------------------------------------+------------+------------+---------+
|           implementation           | old [GB/s] | new [GB/s] | speedup |
+====================================+============+============+=========+
| simdutf::haswell                   |      12.69 |      14.98 | 1.18x   | …
```

base64: add specialisation for compressing

---

tests/base64_tests.cpp
tests/helpers/test.cpp
tests/helpers/test.h

* split tests checking multiple API methods in one procedure
* rename tests to match what they really test; for the sake of complentess: "encoding" = conversion binary data into base64-encoded string; "decoding" = parsing base64-encoded string back into binary data
* update CLI handling to pass also seed value; this required publishing more entities through `test.h` header

base64test: split tests and update CLI

---

benchmarks/src/benchmark.cpp
benchmarks/src/benchmark.h
benchmarks/src/benchmark_base.h

Adding a new benchmarks was rather cumbersome (and error prone). With the new code it's required to add implementation (a method), and register it in a single place.

benchmarks: refactor registering benchmarks

---

singleheader/amalgamate.py
src/haswell/implementation.cpp
src/implementation.cpp
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/westmere/implementation.cpp

Make it more robust. Also fix markers.
Addressing issue #683.

amalgamate.py: fix parsing of #endif

---

tests/convert_utf8_to_utf16be_tests.cpp

We recently added some new tests, just prior to our latest release. But these tests were not vetted on big endian systems. They implicitly assume that we are running under a little endian system.
This PR disables the new tests on big endian systems. They will only run on little endian systems.
Fixes https://github.com/simdutf/simdutf/issues/702

disabling the new tests on big endian systems

---

scripts/.flake8
scripts/base64bench_print.py
scripts/benchmark_print.py
scripts/table.py

RestructuredText is not as widespread as Markdown. Switch the table format to Markdown, so output can be pasted directly on GitHub (for instance).

scripts: output tables in Markdown format

---

include/simdutf/implementation.h
src/arm64/arm_base64.cpp
src/haswell/avx2_base64.cpp
src/simdutf/haswell/bitmanipulation.h
src/westmere/sse_base64.cpp

@WojciechMula recently pushed a nice optimization to the Westmere and Haswell kernels. We can port it to ARM.
Here are the results on my M2 macBook.
Command:
```
cmake --build build --target benchmark_base64  && ./build/benchmarks/base64/benchmark_base64 -d ../base64data/dns/swedenzonebase.txt
```
Before:
```
simdutf::arm64                           :   5.52 GB/s  2.51 % 
simdutf::arm64 (accept garbage)          :   5.70 GB/s  1.78 % 
```
After:
```
simdutf::arm64                           :   6.20 GB/s  3.11 % 
simdutf::arm64 (accept garbage)          :   6.86 GB/s  2.43 % 
```
So that's a performance boost of about 10%... which is well worth it.
The downside of this approach is more branching and slightly more complexity, so it is possible that the gains do not always translate into …

porting single-compress optimization to arm

---

src/generic/base64.h
src/haswell/avx2_base64.cpp
src/haswell/implementation.cpp
src/simdutf/haswell/bitmanipulation.h
src/simdutf/westmere/bitmanipulation.h
src/westmere/implementation.cpp
src/westmere/sse_base64.cpp

This is the first step of larger refactoring. While base64 decoding itself is not complicated, the correct handling of different options we provide is quite difficult.
Having this piece of code in a single place would make future extending the code (like adding a new target) easier and less error-prone.
The main change is making most free-standing procedures methods of the `block64` class.

base64: factor out common decoding template

---

src/simdutf/haswell/simd32-inl.h
src/simdutf/haswell/simd64-inl.h
src/simdutf/icelake/bitmanipulation.h
src/simdutf/lasx/bitmanipulation.h
src/simdutf/lsx/bitmanipulation.h
src/simdutf/westmere/simd32-inl.h
src/simdutf/westmere/simd64-inl.h

Unfortunately, instead of just optimizing it out, LLVM/clang sees fit to issue warnings. So we comment them out (we may need them later).
This is a bit of a waste of time.
Fixes https://github.com/simdutf/simdutf/issues/709

A small numbers of constants and functions are not actively used.

---

benchmarks/src/benchmark.cpp
benchmarks/src/benchmark.h
src/generic/utf16.h
src/haswell/implementation.cpp
src/simdutf/haswell/simd16-inl.h
src/simdutf/westmere/simd16-inl.h
src/westmere/implementation.cpp
tests/CMakeLists.txt
tests/convert_utf16le_to_utf8_tests.cpp
tests/utf8_length_from_utf16_tests.cpp

This PR uses similar approach used previously to speed-up UTF-8 length from UTF-32 --- that is, don't convert byte-mask into bit-mask, but use vector counters, that from time-to-time update scalar counter.
Results for `./benchmark -P utf8_length_from_utf16le -F unicode_lipsum/wikipedia_mars/*.utf16.txt`.
|              dataset              | size [B] | iterations | old GB/s | new GB/s | speedup |
| --------------------------------- | -------- | ---------- | -------- | -------- | ------- |
| utf8_length_from_utf16le+haswell                                                          |
| arabic.utf16                      |   849688 |      30000 |     6.59 |    12.74 | 1.93x   |
| chinese.utf16                     |   274416 |      30000 |     6.59 |    12.72 | 1.93x   |
| czech.utf16 …

Faster UTF-8 length from UTF-16

---

src/lasx/lasx_validate_utf16.cpp
src/simdutf/lasx/simd16-inl.h

Tested on real machine, all tests pass with this fix.
Issue #717

lasx: fix validate UTF-16

---

benchmarks/src/benchmark.cpp
benchmarks/src/benchmark.h
benchmarks/src/cmdline.cpp
benchmarks/src/cmdline.h
scripts/benchmark-all.py

Also extend `benchmark` utility to export benchmark specs in JSON format.
This is the first step to fill database https://github.com/simdutf/benchmark-results.

scripts: add script that collects all benchmarks

---

src/icelake/icelake_utf8_length_from_utf16.inl.cpp
src/icelake/implementation.cpp
src/simdutf/icelake/simd.h
src/simdutf/icelake/simd16-inl.h

Use a similar approach as the generic implementation, that is keep counters in vector registers.
Benchmark results for `./build/benchmarks/benchmark -P utf8_length_from_utf16le+icelake -F ~/unicode_lipsum/wikipedia_mars/*.utf16.txt -I 10000`
|             dataset              | size [B] | iterations | old GB/s | new GB/s | speedup |
| -------------------------------- | -------- | ---------- | -------- | -------- | ------- |
| utf8_length_from_utf16le+icelake                                                         |
| arabic.utf16                     |   849688 |      10000 |     7.65 |    12.19 | 1.59x   |
| chinese.utf16                    |   274416 |      10000 |     7.64 |    12.21 | 1.60x   |
| czech.utf16                      |   287664 |      10000 |     7.63 |    12.21 | 1.60x   | …

icelake: faster UTF-8 length from UTF-16

---

src/lasx/implementation.cpp
src/lasx/lasx_base64.cpp
src/lasx/lasx_convert_latin1_to_utf8.cpp
src/lasx/lasx_convert_utf16_to_utf32.cpp
src/lasx/lasx_convert_utf16_to_utf8.cpp
src/lasx/lasx_convert_utf32_to_utf16.cpp
src/lasx/lasx_convert_utf32_to_utf8.cpp
src/lasx/lasx_convert_utf8_to_utf16.cpp
src/lasx/lasx_convert_utf8_to_utf32.cpp
src/lasx/lasx_validate_utf32le.cpp
src/lsx/implementation.cpp
src/lsx/lsx_base64.cpp
src/lsx/lsx_convert_latin1_to_utf8.cpp
src/lsx/lsx_convert_utf16_to_utf32.cpp
src/lsx/lsx_convert_utf16_to_utf8.cpp
src/lsx/lsx_convert_utf32_to_utf16.cpp
src/lsx/lsx_convert_utf32_to_utf8.cpp
src/lsx/lsx_convert_utf8_to_utf16.cpp
src/lsx/lsx_convert_utf8_to_utf32.cpp
src/lsx/lsx_validate_utf32le.cpp
src/simdutf/lasx/intrinsics.h
src/simdutf/lsx/intrinsics.h

The intrinsics for LSX and LASX do not provide opaque broadcast/splat functions, similar to _mm_set1_epiXX known from SSE. It's a programmer responsible to pick a correct instruction. Also, a powerful `vldi` instruction comes with no support for building "magic" constants.
This set of templates should help in everyday vectorization, and for sure make code more readable.

lsx & lasx: add splat intrinsics

---

src/rvv/rvv_utf8_to.inl.cpp
src/rvv/rvv_validate.inl.cpp

In C/C++, that char type is neither signed or unsigned, it is implementation defined. A right shift on a signed type is implementation defined. Thus, if `src` is a pointer to char values, then `src[idx] >> 6` may or may not do what you think.
We had the pattern `(src[idx] >> 6) == 0b10` everywhere in the RISC-V kernel, but in many cases, `(src[0] >> 6) == 0b10` is going to be false (always). 
It is possible that when compiling on RISC-V, chars might be considered unsigned. Maybe it is always so. I do not know. It is so under GCC when compiling to RISC-V, see https://godbolt.org/z/PKqxTPh1r
Still, it seems like a risky proposition to make this assumption !!!
Fixes https://github.com/simdutf/simdutf/issues/728

Some code in the RVV kernel assumes that char is unsigned

---

src/arm64/arm_base64.cpp

This is an attempt to reduce the instruction count from 11 to 9 as seen in the below Compiler Explorer link
https://godbolt.org/z/Krze65Kcs
Before:
```
./build/benchmarks/base64/benchmark_base64 -f simdutf -d base64data/email/*
simdutf::arm64                           :   7.53 GB/s  2.30 %
simdutf::arm64 (accept garbage)          :   7.58 GB/s  1.90 %
```
After:
```
./build2/benchmarks/base64/benchmark_base64 -f simdutf -d base64data/email/*
simdutf::arm64                           :   7.75 GB/s  2.33 %
simdutf::arm64 (accept garbage)          :   7.73 GB/s  2.35 %
```

arm64: optimize base64 decode block by replacing ORR + SHL + SHR with SLI + SHR

---

fuzz/random_fuzz.sh
src/lasx/lasx_convert_latin1_to_utf16.cpp
src/lasx/lasx_convert_latin1_to_utf8.cpp
src/simdutf/lasx/intrinsics.h
src/simdutf/lsx/intrinsics.h

An error occurs when running `random_fuzz.sh`
```
[ 50%] Building CXX object src/CMakeFiles/simdutf.dir/simdutf.cpp.o
In file included from /home/xiaotao/simd/simdutf/src/simdutf.cpp:28:
In file included from /home/xiaotao/simd/simdutf/src/simdutf/lsx.h:36:
/home/xiaotao/simd/simdutf/src/simdutf/lsx/intrinsics.h:172:22: fatal error: argument value 7936 is outside the valid range [-512, 511]
172 |   return is_imm10  ? __lsx_vrepli_h(int16_t(x))
|                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-19/lib/clang/19/include/lsxintrin.h:3745:47: note: expanded from macro '__lsx_vrepli_h' …
```

fix LoongArch64 fuzz error

---

include/simdutf/implementation.h

I can't find the function `maximal_binary_length_from_utf6_base64`.
Finally, I realized it was a typo.

fix typos in base64_to_binary documents

---

tests/base64_tests.cpp

I believe that issue https://bugs.webkit.org/show_bug.cgi?id=290829 in WebKit has long been fixed in simdutf, but let us add a test to be sure.

adding a test for a WebKit issue

---

src/simdutf/arm64/simd.h
src/simdutf/arm64/simd16-inl.h
src/simdutf/haswell/simd.h
src/simdutf/haswell/simd16-inl.h
src/simdutf/westmere/simd.h
src/simdutf/westmere/simd16-inl.h

The wrappers for these targets expose way more functions that are really needed. The unused methods and fields got removed.

arm64, haswell, westmere: trim SIMD wrappers

---

src/generic/validate_utf32.h
src/simdutf/haswell/simd32-inl.h
src/simdutf/ppc64/simd32-inl.h
src/simdutf/westmere/simd32-inl.h

Make the implementation of validator more friendly for SSE (do not use `greater than`, as SSE does not support it for unsigned numbers) and also simplify conditions to test surrogates.
Improvements are not too big, but some number of CPU cycles got shaved.
Benchmark for `./benchmark -P validate_utf32_with_errors -F ~/unicode_lipsum/wikipedia_mars/*.utf32.txt -I 1000`
|               dataset               | size [B] | iterations | old GB/s | new GB/s | speedup |
| ----------------------------------- | -------- | ---------- | -------- | -------- | ------- |
| validate_utf32_with_errors+fallback                                                         |
| arabic.utf32                        |  1699376 |       1000 |    12.10 |    12.10 | 1.00x   |
| chinese.utf32                       | …

a bit faster generic validate UTF32 with errors

---

benchmarks/benchmark.cpp
benchmarks/src/benchmark.h
src/icelake/icelake_common.inl.cpp
src/icelake/implementation.cpp

Based on #741
[mula@localhost simdutf]$ ./scripts/benchmark_print.py build/benchmarks/{old,new}
|             dataset             | size [B] | iterations | old GB/s | new GB/s | speedup |
| ------------------------------- | -------- | ---------- | -------- | -------- | ------- |
| utf16_length_from_utf8+icelake                                                          |
| arabic.utf8                     |   533857 |      30000 |    38.29 |    46.12 | 1.20x   |

Icelake: faster UTF-16 length from UTF-8

---

src/arm64/arm_convert_utf32_to_utf16.cpp

I observed that the routine does a narrow from 32 to 16 and uses 8byte SIMD.
This PR processes 32 bytes in the loop instead of 16 and upgrades the instructions to process ~2x compared to previous one.
Further surrogate loop optimization can be done separately.
Before:
```
convert_utf32_to_utf16be+arm64, input size: 260, iterations: 30000, dataset: testutf32.txt
15.182 GB/s (14.9 %)    3.737 Gc/s     4.06 byte/char     17.1 ns
WARNING: Measurements are noisy, try increasing iteration count (-I).
convert_utf32_to_utf16be_with_errors+arm64, input size: 260, iterations: 30000, dataset: testutf32.txt
13.520 GB/s (9.8 %)    3.328 Gc/s     4.06 byte/char     19.2 ns
convert_utf32_to_utf16le+arm64, input size: 260, iterations: 30000, dataset: testutf32.txt
17.660 GB/s (17.4 %)    4.347 Gc/s …
```

arm64: optimized utf32_to_utf16 for regular non-surrogate case

---

src/rvv/rvv_utf32_to.inl.cpp

Use simpler conditions, taking into account that `vfirst` returns -1 when the mask is empty. Number -1 cast to unsigned is always greater than the max positive `vfirst` value.

rvv: simplify UTF-32 to UTF-{8,16}

---

src/lsx/lsx_validate_utf16.cpp
src/simdutf/lasx/simd.h
src/simdutf/lasx/simd16-inl.h
src/simdutf/lsx/simd.h
src/simdutf/lsx/simd16-inl.h

The wrappers for these targets expose way more functions that are really needed. The unused methods and fields got removed.

lsx, lasx: trim SIMD wrappers

---

src/generic/utf16/change_endianness.h
src/generic/utf16/count_code_points_bytemask.h
src/generic/utf16/utf32_length_from_utf16.h
src/generic/utf16/utf8_length_from_utf16.h
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/simdutf/lasx/simd16-inl.h
src/simdutf/lsx/simd16-inl.h

System:
```
CPU Family		: Loongson-64bit
Model Name		: Loongson-3C5000L-LL
```
Benchmark
```shell
$ ./benchmark -P count_utf16 -F ~/unicode_lipsum/wikipedia_mars/*.utf16.txt -I 1000
```
|     dataset      | size [B] | iterations | old GB/s | new GB/s | speedup |
| ---------------- | -------- | ---------- | -------- | -------- | ------- |
| count_utf16+lasx                                                         |
| arabic.utf16     |   849690 |       1000 |     8.85 |    14.38 | 1.62x   |
| chinese.utf16    |   274418 |       1000 |     7.94 |    14.32 | 1.80x   |
| czech.utf16      |   287666 |       1000 |     7.67 |    13.67 | 1.78x   |
| english.utf16    |   775020 |       1000 |     8.84 |    14.54 | 1.64x   |
| esperanto.utf16  |   168252 |       1000 |     7.50 |    14.67 | 1.96x …

lsx, lasx: faster count UTF-16

---

src/rvv/rvv_utf8_to.inl.cpp
src/rvv/rvv_validate.inl.cpp

Use the 8-bit shift instead of the 16-bit shifts followed by bit-and.

rvv: simplify UTF-8 validation

---

src/arm64/arm_convert_utf32_to_utf16.cpp

Logic is based on the westmere code and the ongoing haswell https://github.com/simdutf/simdutf/pull/738
In the worst case, the 4 utf32 words could map to 4 non-surrogate utf16 words. 
Thus the vector store would have 8 bytes overrun. To prevent buffer overflow, 4 words safety margin is introduced.
Verified that unit tests pass with SIMDUTF_SANITIZER enabled.

Vectorized the aarch64 utf32 to utf16 surrogate handling loop using NEON

---

src/arm64/arm_convert_utf32_to_utf16.cpp

On ARM systems with weak SIMD, PR https://github.com/simdutf/simdutf/pull/749 lead to a significant performance loss in the case where there is no possible surrogate when transcoding from utf-32 to utf-16.
The issue seems to be poor code generation. The fix is to help the compiler a bit with a hint.
With GCC 13 on a Graviton 2 (Neoverse N1), I get the following gains:
|            dataset             | size [B] | iterations | old GB/s | new GB/s | speedup |
| ------------------------------ | -------- | ---------- | -------- | -------- | ------- |
| convert_utf32_to_utf16le+arm64                                                         |
| 256k_000perc_surrogates.utf32  |  1048576 |      30000 |     3.21 |    15.73 | 4.91x   |
| 256k_005perc_surrogates.utf32  |  1048576 |      30000 | …

recovering some of the lost speed in utf-32 to utf-16 (arm) when there is no surrogate handling

---

.github/workflows/ubuntu24sani.yml
include/simdutf/implementation.h
src/implementation.cpp
tests/atomic_base64_tests.cpp

We added atomic_binary_to_base64 to meet the needs of 
https://github.com/simdutf/simdutf/issues/658
But we made it too atomic. The request was for *atomic reads*.

atomic_binary_to_base64 is too atomic: the requested feature was atomic reads

---

include/simdutf/implementation.h
src/implementation.cpp
tests/span_tests.cpp

fixes #761 
this also revealed an unrelated bug - there were no implementations of convert_valid_utf32_to_latin1 and convert_utf32_to_latin1_with_errors.
those functions are tested but use the implementation member function, that is why it was undetected.
this tells me there is probably noone using those functions!

fix missing const in std::span inputs

---

src/generic/utf16/to_well_formed.h
src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/simdutf/lasx/simd16-inl.h
src/simdutf/lsx/simd16-inl.h

Finally run it on a real machine, performance is quite good, IMHO.
Machine:
```
CPU Family		: Loongson-64bit
Model Name		: Loongson-3C5000L-LL
```
Benchmark results:
|     dataset      | run_to_well_formed_utf16+lasx | run_to_well_formed_utf16+lsx |
| ---------------- | ----------------------------- | ---------------------------- |
| arabic.utf16     | 6.795 GB/s                    | 5.949 GB/s                   |
| chinese.utf16    | 7.156 GB/s                    | 5.932 GB/s                   |
| czech.utf16      | 6.969 GB/s                    | 5.919 GB/s                   |
| english.utf16    | 7.054 GB/s                    | 5.953 GB/s                   |
| esperanto.utf16  | 6.996 GB/s                    | 5.475 GB/s                   |
| french.utf16     | 6.790 GB/s …

LoongArch64: implement `to_well_formed_utf16`

---

README.md
include/simdutf/implementation.h
src/implementation.cpp
tests/base64_tests.cpp

When decoding base64, if we encounter an invalid character, we do not always exit after trying to write out as much output as possible. (Our spec does not says so.) This PR adds a slow path that writes out as much as possible.
The core of the issue is that the JavaScript spec assumes a slow, tiny block by tiny block, decoding. We decoding in a more sophisticated and considerably faster manner.
This should fix issue https://bugs.webkit.org/show_bug.cgi?id=290829 
We add a test using UTF-16 inputs.

Address WebKit Issue 290829: Maximize output in base64_to_binary_safe when an invalid character is encountered.

---

src/scalar/atomic_util.h
tests/atomic_base64_tests.cpp

this fixes two minor issues.
The first one is a scope issue in the atomic thread test. I discovered this by accident when fiddling around with the threaded test when running without thread sanitizer, but with address sanitizer.
The other is a temporary hack I committed by mistake. I believe it is harmless because it is only included in c++20 anyway, but it shall be removed regardless.

Fix scope error in atomic thread test

---

src/icelake/implementation.cpp
src/rvv/rvv_validate.inl.cpp

We need only inspect most significant byte. In the case of icelake kernel `pshufb` is replaced with shift --- it's not a big change, just noticed that AMD Zen4 has latency 1 cycle for shift , and 2 cycles for pshufb.
In the case of rvv we completely rid of endianness changing, resulting in the same code for LE and BE variants.

Simplify `validate_utf16be` for icelake and rvv

---

src/rvv/rvv_validate.inl.cpp

Shave one instruction from the hot path.

rvv: a bit simpler UTF-8 validation

---

CONTRIBUTING.md
README.md
benchmarks/src/benchmark.cpp
benchmarks/src/benchmark.h
include/simdutf/implementation.h
src/implementation.cpp
src/ppc64/implementation.cpp
src/scalar/utf16.h
src/scalar/utf16_to_utf8/utf16_to_utf8.h
tests/CMakeLists.txt
tests/convert_utf16_to_utf8_safe_tests.cpp

Effectively, allows us to transcode from UTF-16 to UTF-8 with a limit on the number of bytes that we are allowed to write. We try to write as many bytes as possible before exiting.
Fixes https://github.com/simdutf/simdutf/issues/725 described by @syg
I have not experimented with the implementation but I have added benchmarks and the performance looks quite good with the simple implementation that I have provided.

 _safe variant of convert_utf16_to_utf8 

---

include/simdutf/error.h

Enabling `C++ Core Guidelines` analysis warnings for function rules in MSVC reports C26440, C26455 and C26447 warnings in `error.h` header when `simdutf.h` is included from user code.
Marking the problematic functions as `noexcept` resolves the issue and as far as I could see, there's no reason for them to not be marked as such.

Fix MSVC noexcept analysis warnings

---

src/lasx/implementation.cpp
src/lsx/implementation.cpp
src/ppc64/implementation.cpp

Enable SIMD generic validate_utf16_as_ascii for lsx + lasx + ppc64
